// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud
{
    /// <summary>
    /// Provisions a Temporal Cloud Connectivity Rule.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Temporalcloud = GripSecurity.Temporalcloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Create Public Connectivity Rule
    ///     var publicRule = new Temporalcloud.ConnectivityRule("public_rule", new()
    ///     {
    ///         ConnectivityType = "public",
    ///     });
    /// 
    ///     // Create Private Connectivity Rule for AWS
    ///     var privateAws = new Temporalcloud.ConnectivityRule("private_aws", new()
    ///     {
    ///         ConnectivityType = "private",
    ///         ConnectionId = "vpce-12345678",
    ///         Region = "aws-us-west-2",
    ///     });
    /// 
    ///     // Create Private Connectivity Rule for GCP
    ///     var privateGcp = new Temporalcloud.ConnectivityRule("private_gcp", new()
    ///     {
    ///         ConnectivityType = "private",
    ///         ConnectionId = "vpce-12345678",
    ///         Region = "gcp-us-central1",
    ///         GcpProjectId = "my-gcp-project-id",
    ///     });
    /// 
    ///     // Attaching connectivity rules to a namespace
    ///     var ns_with_cr = new Temporalcloud.Namespace("ns-with-cr", new()
    ///     {
    ///         Name = "ns-with-cr",
    ///         Regions = new[]
    ///         {
    ///             "aws-us-west-2",
    ///         },
    ///         ApiKeyAuth = true,
    ///         RetentionDays = 14,
    ///         ConnectivityRuleIds = new[]
    ///         {
    ///             id,
    ///             idPrivateAws,
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [TemporalcloudResourceType("temporalcloud:index/connectivityRule:ConnectivityRule")]
    public partial class ConnectivityRule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The connection ID of the private connection.
        /// </summary>
        [Output("connectionId")]
        public Output<string?> ConnectionId { get; private set; } = null!;

        /// <summary>
        /// The type of connectivity. Must be one of 'public' or 'private'.
        /// </summary>
        [Output("connectivityType")]
        public Output<string> ConnectivityType { get; private set; } = null!;

        /// <summary>
        /// The GCP project ID. Required when cloud_provider is 'gcp'.
        /// </summary>
        [Output("gcpProjectId")]
        public Output<string?> GcpProjectId { get; private set; } = null!;

        /// <summary>
        /// The region of the connection. Example: 'aws-us-west-2'.
        /// </summary>
        [Output("region")]
        public Output<string?> Region { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.ConnectivityRuleTimeouts?> Timeouts { get; private set; } = null!;


        /// <summary>
        /// Create a ConnectivityRule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ConnectivityRule(string name, ConnectivityRuleArgs args, CustomResourceOptions? options = null)
            : base("temporalcloud:index/connectivityRule:ConnectivityRule", name, args ?? new ConnectivityRuleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ConnectivityRule(string name, Input<string> id, ConnectivityRuleState? state = null, CustomResourceOptions? options = null)
            : base("temporalcloud:index/connectivityRule:ConnectivityRule", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/Grip-Security/pulumi-temporalcloud/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ConnectivityRule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ConnectivityRule Get(string name, Input<string> id, ConnectivityRuleState? state = null, CustomResourceOptions? options = null)
        {
            return new ConnectivityRule(name, id, state, options);
        }
    }

    public sealed class ConnectivityRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The connection ID of the private connection.
        /// </summary>
        [Input("connectionId")]
        public Input<string>? ConnectionId { get; set; }

        /// <summary>
        /// The type of connectivity. Must be one of 'public' or 'private'.
        /// </summary>
        [Input("connectivityType", required: true)]
        public Input<string> ConnectivityType { get; set; } = null!;

        /// <summary>
        /// The GCP project ID. Required when cloud_provider is 'gcp'.
        /// </summary>
        [Input("gcpProjectId")]
        public Input<string>? GcpProjectId { get; set; }

        /// <summary>
        /// The region of the connection. Example: 'aws-us-west-2'.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("timeouts")]
        public Input<Inputs.ConnectivityRuleTimeoutsArgs>? Timeouts { get; set; }

        public ConnectivityRuleArgs()
        {
        }
        public static new ConnectivityRuleArgs Empty => new ConnectivityRuleArgs();
    }

    public sealed class ConnectivityRuleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The connection ID of the private connection.
        /// </summary>
        [Input("connectionId")]
        public Input<string>? ConnectionId { get; set; }

        /// <summary>
        /// The type of connectivity. Must be one of 'public' or 'private'.
        /// </summary>
        [Input("connectivityType")]
        public Input<string>? ConnectivityType { get; set; }

        /// <summary>
        /// The GCP project ID. Required when cloud_provider is 'gcp'.
        /// </summary>
        [Input("gcpProjectId")]
        public Input<string>? GcpProjectId { get; set; }

        /// <summary>
        /// The region of the connection. Example: 'aws-us-west-2'.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("timeouts")]
        public Input<Inputs.ConnectivityRuleTimeoutsGetArgs>? Timeouts { get; set; }

        public ConnectivityRuleState()
        {
        }
        public static new ConnectivityRuleState Empty => new ConnectivityRuleState();
    }
}
