// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud
{
    public static class GetNexusEndpoint
    {
        /// <summary>
        /// Fetches details about a Nexus Endpoint.
        /// </summary>
        public static Task<GetNexusEndpointResult> InvokeAsync(GetNexusEndpointArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNexusEndpointResult>("temporalcloud:index/getNexusEndpoint:getNexusEndpoint", args ?? new GetNexusEndpointArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches details about a Nexus Endpoint.
        /// </summary>
        public static Output<GetNexusEndpointResult> Invoke(GetNexusEndpointInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNexusEndpointResult>("temporalcloud:index/getNexusEndpoint:getNexusEndpoint", args ?? new GetNexusEndpointInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches details about a Nexus Endpoint.
        /// </summary>
        public static Output<GetNexusEndpointResult> Invoke(GetNexusEndpointInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNexusEndpointResult>("temporalcloud:index/getNexusEndpoint:getNexusEndpoint", args ?? new GetNexusEndpointInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNexusEndpointArgs : global::Pulumi.InvokeArgs
    {
        [Input("description")]
        private string? _description;

        /// <summary>
        /// The description of the Nexus Endpoint.
        /// </summary>
        public string? Description
        {
            get => _description;
            set => _description = value;
        }

        /// <summary>
        /// The unique identifier of the Nexus Endpoint.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetNexusEndpointArgs()
        {
        }
        public static new GetNexusEndpointArgs Empty => new GetNexusEndpointArgs();
    }

    public sealed class GetNexusEndpointInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("description")]
        private Input<string>? _description;

        /// <summary>
        /// The description of the Nexus Endpoint.
        /// </summary>
        public Input<string>? Description
        {
            get => _description;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _description = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The unique identifier of the Nexus Endpoint.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetNexusEndpointInvokeArgs()
        {
        }
        public static new GetNexusEndpointInvokeArgs Empty => new GetNexusEndpointInvokeArgs();
    }


    [OutputType]
    public sealed class GetNexusEndpointResult
    {
        /// <summary>
        /// Namespace Id(s) that are allowed to call this Endpoint.
        /// </summary>
        public readonly ImmutableArray<string> AllowedCallerNamespaces;
        /// <summary>
        /// The creation time of the Nexus Endpoint.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The description of the Nexus Endpoint.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The unique identifier of the Nexus Endpoint.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the endpoint. Unique within an account and match `^[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9]$`
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The current state of the Nexus Endpoint.
        /// </summary>
        public readonly string State;
        /// <summary>
        /// The last update time of the Nexus Endpoint.
        /// </summary>
        public readonly string UpdatedAt;
        /// <summary>
        /// The target spec for routing nexus requests to a specific cloud namespace worker.
        /// </summary>
        public readonly Outputs.GetNexusEndpointWorkerTargetResult WorkerTarget;

        [OutputConstructor]
        private GetNexusEndpointResult(
            ImmutableArray<string> allowedCallerNamespaces,

            string createdAt,

            string description,

            string id,

            string name,

            string state,

            string updatedAt,

            Outputs.GetNexusEndpointWorkerTargetResult workerTarget)
        {
            AllowedCallerNamespaces = allowedCallerNamespaces;
            CreatedAt = createdAt;
            Description = description;
            Id = id;
            Name = name;
            State = state;
            UpdatedAt = updatedAt;
            WorkerTarget = workerTarget;
        }
    }
}
