// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud
{
    public static class GetNamespace
    {
        /// <summary>
        /// Fetches details about a Namespace.
        /// </summary>
        public static Task<GetNamespaceResult> InvokeAsync(GetNamespaceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNamespaceResult>("temporalcloud:index/getNamespace:getNamespace", args ?? new GetNamespaceArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches details about a Namespace.
        /// </summary>
        public static Output<GetNamespaceResult> Invoke(GetNamespaceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNamespaceResult>("temporalcloud:index/getNamespace:getNamespace", args ?? new GetNamespaceInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches details about a Namespace.
        /// </summary>
        public static Output<GetNamespaceResult> Invoke(GetNamespaceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNamespaceResult>("temporalcloud:index/getNamespace:getNamespace", args ?? new GetNamespaceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNamespaceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
        /// </summary>
        [Input("apiKeyAuth")]
        public bool? ApiKeyAuth { get; set; }

        [Input("certificateFilters")]
        private List<Inputs.GetNamespaceCertificateFilterArgs>? _certificateFilters;

        /// <summary>
        /// A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
        /// </summary>
        public List<Inputs.GetNamespaceCertificateFilterArgs> CertificateFilters
        {
            get => _certificateFilters ?? (_certificateFilters = new List<Inputs.GetNamespaceCertificateFilterArgs>());
            set => _certificateFilters = value;
        }

        /// <summary>
        /// A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
        /// </summary>
        [Input("codecServer")]
        public Inputs.GetNamespaceCodecServerArgs? CodecServer { get; set; }

        [Input("customSearchAttributes")]
        private Dictionary<string, string>? _customSearchAttributes;

        /// <summary>
        /// The custom search attributes to use for the namespace.
        /// </summary>
        public Dictionary<string, string> CustomSearchAttributes
        {
            get => _customSearchAttributes ?? (_customSearchAttributes = new Dictionary<string, string>());
            set => _customSearchAttributes = value;
        }

        /// <summary>
        /// The unique identifier of the namespace across all Temporal Cloud tenants.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
        /// </summary>
        [Input("lastModifiedTime")]
        public string? LastModifiedTime { get; set; }

        [Input("privateConnectivities")]
        private List<Inputs.GetNamespacePrivateConnectivityArgs>? _privateConnectivities;

        /// <summary>
        /// The private connectivities for the namespace, if any.
        /// </summary>
        public List<Inputs.GetNamespacePrivateConnectivityArgs> PrivateConnectivities
        {
            get => _privateConnectivities ?? (_privateConnectivities = new List<Inputs.GetNamespacePrivateConnectivityArgs>());
            set => _privateConnectivities = value;
        }

        public GetNamespaceArgs()
        {
        }
        public static new GetNamespaceArgs Empty => new GetNamespaceArgs();
    }

    public sealed class GetNamespaceInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
        /// </summary>
        [Input("apiKeyAuth")]
        public Input<bool>? ApiKeyAuth { get; set; }

        [Input("certificateFilters")]
        private InputList<Inputs.GetNamespaceCertificateFilterInputArgs>? _certificateFilters;

        /// <summary>
        /// A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
        /// </summary>
        public InputList<Inputs.GetNamespaceCertificateFilterInputArgs> CertificateFilters
        {
            get => _certificateFilters ?? (_certificateFilters = new InputList<Inputs.GetNamespaceCertificateFilterInputArgs>());
            set => _certificateFilters = value;
        }

        /// <summary>
        /// A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
        /// </summary>
        [Input("codecServer")]
        public Input<Inputs.GetNamespaceCodecServerInputArgs>? CodecServer { get; set; }

        [Input("customSearchAttributes")]
        private InputMap<string>? _customSearchAttributes;

        /// <summary>
        /// The custom search attributes to use for the namespace.
        /// </summary>
        public InputMap<string> CustomSearchAttributes
        {
            get => _customSearchAttributes ?? (_customSearchAttributes = new InputMap<string>());
            set => _customSearchAttributes = value;
        }

        /// <summary>
        /// The unique identifier of the namespace across all Temporal Cloud tenants.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
        /// </summary>
        [Input("lastModifiedTime")]
        public Input<string>? LastModifiedTime { get; set; }

        [Input("privateConnectivities")]
        private InputList<Inputs.GetNamespacePrivateConnectivityInputArgs>? _privateConnectivities;

        /// <summary>
        /// The private connectivities for the namespace, if any.
        /// </summary>
        public InputList<Inputs.GetNamespacePrivateConnectivityInputArgs> PrivateConnectivities
        {
            get => _privateConnectivities ?? (_privateConnectivities = new InputList<Inputs.GetNamespacePrivateConnectivityInputArgs>());
            set => _privateConnectivities = value;
        }

        public GetNamespaceInvokeArgs()
        {
        }
        public static new GetNamespaceInvokeArgs Empty => new GetNamespaceInvokeArgs();
    }


    [OutputType]
    public sealed class GetNamespaceResult
    {
        /// <summary>
        /// The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud.
        /// </summary>
        public readonly string AcceptedClientCa;
        /// <summary>
        /// The currently active region for the namespace.
        /// </summary>
        public readonly string ActiveRegion;
        /// <summary>
        /// If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
        /// </summary>
        public readonly bool? ApiKeyAuth;
        /// <summary>
        /// A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetNamespaceCertificateFilterResult> CertificateFilters;
        /// <summary>
        /// A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
        /// </summary>
        public readonly Outputs.GetNamespaceCodecServerResult CodecServer;
        /// <summary>
        /// The date and time when the namespace was created.
        /// </summary>
        public readonly string CreatedTime;
        /// <summary>
        /// The custom search attributes to use for the namespace.
        /// </summary>
        public readonly ImmutableDictionary<string, string> CustomSearchAttributes;
        /// <summary>
        /// The endpoints for the namespace.
        /// </summary>
        public readonly Outputs.GetNamespaceEndpointsResult Endpoints;
        /// <summary>
        /// The unique identifier of the namespace across all Temporal Cloud tenants.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
        /// </summary>
        public readonly string LastModifiedTime;
        /// <summary>
        /// The limits set on the namespace currently.
        /// </summary>
        public readonly Outputs.GetNamespaceLimitsResult Limits;
        /// <summary>
        /// The name of the namespace.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The private connectivities for the namespace, if any.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetNamespacePrivateConnectivityResult> PrivateConnectivities;
        public readonly ImmutableArray<string> Regions;
        /// <summary>
        /// The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
        /// </summary>
        public readonly int RetentionDays;
        /// <summary>
        /// The current state of the namespace.
        /// </summary>
        public readonly string State;

        [OutputConstructor]
        private GetNamespaceResult(
            string acceptedClientCa,

            string activeRegion,

            bool? apiKeyAuth,

            ImmutableArray<Outputs.GetNamespaceCertificateFilterResult> certificateFilters,

            Outputs.GetNamespaceCodecServerResult codecServer,

            string createdTime,

            ImmutableDictionary<string, string> customSearchAttributes,

            Outputs.GetNamespaceEndpointsResult endpoints,

            string id,

            string lastModifiedTime,

            Outputs.GetNamespaceLimitsResult limits,

            string name,

            ImmutableArray<Outputs.GetNamespacePrivateConnectivityResult> privateConnectivities,

            ImmutableArray<string> regions,

            int retentionDays,

            string state)
        {
            AcceptedClientCa = acceptedClientCa;
            ActiveRegion = activeRegion;
            ApiKeyAuth = apiKeyAuth;
            CertificateFilters = certificateFilters;
            CodecServer = codecServer;
            CreatedTime = createdTime;
            CustomSearchAttributes = customSearchAttributes;
            Endpoints = endpoints;
            Id = id;
            LastModifiedTime = lastModifiedTime;
            Limits = limits;
            Name = name;
            PrivateConnectivities = privateConnectivities;
            Regions = regions;
            RetentionDays = retentionDays;
            State = state;
        }
    }
}
