// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Temporalcloud
{
    public static class GetServiceAccounts
    {
        /// <summary>
        /// Fetches details about all Service Accounts.
        /// </summary>
        public static Task<GetServiceAccountsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetServiceAccountsResult>("temporalcloud:index/getServiceAccounts:getServiceAccounts", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Fetches details about all Service Accounts.
        /// </summary>
        public static Output<GetServiceAccountsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetServiceAccountsResult>("temporalcloud:index/getServiceAccounts:getServiceAccounts", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Fetches details about all Service Accounts.
        /// </summary>
        public static Output<GetServiceAccountsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetServiceAccountsResult>("temporalcloud:index/getServiceAccounts:getServiceAccounts", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetServiceAccountsResult
    {
        /// <summary>
        /// The unique identifier of the Service Accounts data source.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of Service Accounts.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetServiceAccountsServiceAccountResult> ServiceAccounts;

        [OutputConstructor]
        private GetServiceAccountsResult(
            string id,

            ImmutableArray<Outputs.GetServiceAccountsServiceAccountResult> serviceAccounts)
        {
            Id = id;
            ServiceAccounts = serviceAccounts;
        }
    }
}
