// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud
{
    public static class GetScimGroup
    {
        /// <summary>
        /// Fetches details about a SCIM group.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Temporalcloud = Pulumi.Temporalcloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myScimGroup = new Temporalcloud.Index.ScimGroup("my_scim_group", new()
        ///     {
        ///         IdpId = "usually-group-name",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["scimGroup"] = myScimGroupTemporalcloudScimGroup,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetScimGroupResult> InvokeAsync(GetScimGroupArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetScimGroupResult>("temporalcloud:index/getScimGroup:getScimGroup", args ?? new GetScimGroupArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches details about a SCIM group.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Temporalcloud = Pulumi.Temporalcloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myScimGroup = new Temporalcloud.Index.ScimGroup("my_scim_group", new()
        ///     {
        ///         IdpId = "usually-group-name",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["scimGroup"] = myScimGroupTemporalcloudScimGroup,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetScimGroupResult> Invoke(GetScimGroupInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetScimGroupResult>("temporalcloud:index/getScimGroup:getScimGroup", args ?? new GetScimGroupInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches details about a SCIM group.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Temporalcloud = Pulumi.Temporalcloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myScimGroup = new Temporalcloud.Index.ScimGroup("my_scim_group", new()
        ///     {
        ///         IdpId = "usually-group-name",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["scimGroup"] = myScimGroupTemporalcloudScimGroup,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetScimGroupResult> Invoke(GetScimGroupInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetScimGroupResult>("temporalcloud:index/getScimGroup:getScimGroup", args ?? new GetScimGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetScimGroupArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The IDP ID of the SCIM group.
        /// </summary>
        [Input("idpId", required: true)]
        public string IdpId { get; set; } = null!;

        public GetScimGroupArgs()
        {
        }
        public static new GetScimGroupArgs Empty => new GetScimGroupArgs();
    }

    public sealed class GetScimGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The IDP ID of the SCIM group.
        /// </summary>
        [Input("idpId", required: true)]
        public Input<string> IdpId { get; set; } = null!;

        public GetScimGroupInvokeArgs()
        {
        }
        public static new GetScimGroupInvokeArgs Empty => new GetScimGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetScimGroupResult
    {
        /// <summary>
        /// The ID of the SCIM group.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The IDP ID of the SCIM group.
        /// </summary>
        public readonly string IdpId;
        /// <summary>
        /// The name of the SCIM group.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetScimGroupResult(
            string id,

            string idpId,

            string name)
        {
            Id = id;
            IdpId = idpId;
            Name = name;
        }
    }
}
