// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud
{
    public static class GetServiceAccount
    {
        /// <summary>
        /// Fetches details about a Service Account.
        /// </summary>
        public static Task<GetServiceAccountResult> InvokeAsync(GetServiceAccountArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetServiceAccountResult>("temporalcloud:index/getServiceAccount:getServiceAccount", args ?? new GetServiceAccountArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches details about a Service Account.
        /// </summary>
        public static Output<GetServiceAccountResult> Invoke(GetServiceAccountInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetServiceAccountResult>("temporalcloud:index/getServiceAccount:getServiceAccount", args ?? new GetServiceAccountInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches details about a Service Account.
        /// </summary>
        public static Output<GetServiceAccountResult> Invoke(GetServiceAccountInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetServiceAccountResult>("temporalcloud:index/getServiceAccount:getServiceAccount", args ?? new GetServiceAccountInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetServiceAccountArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier of the Service Account.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("namespaceAccesses")]
        private List<Inputs.GetServiceAccountNamespaceAccessArgs>? _namespaceAccesses;

        /// <summary>
        /// The set of namespace permissions for this service account, including each namespace and its role.
        /// </summary>
        public List<Inputs.GetServiceAccountNamespaceAccessArgs> NamespaceAccesses
        {
            get => _namespaceAccesses ?? (_namespaceAccesses = new List<Inputs.GetServiceAccountNamespaceAccessArgs>());
            set => _namespaceAccesses = value;
        }

        public GetServiceAccountArgs()
        {
        }
        public static new GetServiceAccountArgs Empty => new GetServiceAccountArgs();
    }

    public sealed class GetServiceAccountInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier of the Service Account.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("namespaceAccesses")]
        private InputList<Inputs.GetServiceAccountNamespaceAccessInputArgs>? _namespaceAccesses;

        /// <summary>
        /// The set of namespace permissions for this service account, including each namespace and its role.
        /// </summary>
        public InputList<Inputs.GetServiceAccountNamespaceAccessInputArgs> NamespaceAccesses
        {
            get => _namespaceAccesses ?? (_namespaceAccesses = new InputList<Inputs.GetServiceAccountNamespaceAccessInputArgs>());
            set => _namespaceAccesses = value;
        }

        public GetServiceAccountInvokeArgs()
        {
        }
        public static new GetServiceAccountInvokeArgs Empty => new GetServiceAccountInvokeArgs();
    }


    [OutputType]
    public sealed class GetServiceAccountResult
    {
        /// <summary>
        /// The role on the account. Must be one of admin, developer, or read (case-insensitive).
        /// </summary>
        public readonly string AccountAccess;
        /// <summary>
        /// The creation time of the Service Account.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The description of the Service Account.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The unique identifier of the Service Account.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name associated with the service account.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The set of namespace permissions for this service account, including each namespace and its role.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetServiceAccountNamespaceAccessResult> NamespaceAccesses;
        /// <summary>
        /// The current state of the Service Account.
        /// </summary>
        public readonly string State;
        /// <summary>
        /// The last update time of the Service Account.
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetServiceAccountResult(
            string accountAccess,

            string createdAt,

            string description,

            string id,

            string name,

            ImmutableArray<Outputs.GetServiceAccountNamespaceAccessResult> namespaceAccesses,

            string state,

            string updatedAt)
        {
            AccountAccess = accountAccess;
            CreatedAt = createdAt;
            Description = description;
            Id = id;
            Name = name;
            NamespaceAccesses = namespaceAccesses;
            State = state;
            UpdatedAt = updatedAt;
        }
    }
}
