// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud
{
    /// <summary>
    /// Provisions Temporal Cloud group access.
    /// </summary>
    [TemporalcloudResourceType("temporalcloud:index/groupAccess:GroupAccess")]
    public partial class GroupAccess : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
        /// </summary>
        [Output("accountAccess")]
        public Output<string> AccountAccess { get; private set; } = null!;

        /// <summary>
        /// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
        /// </summary>
        [Output("namespaceAccesses")]
        public Output<ImmutableArray<Outputs.GroupAccessNamespaceAccess>> NamespaceAccesses { get; private set; } = null!;


        /// <summary>
        /// Create a GroupAccess resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GroupAccess(string name, GroupAccessArgs args, CustomResourceOptions? options = null)
            : base("temporalcloud:index/groupAccess:GroupAccess", name, args ?? new GroupAccessArgs(), MakeResourceOptions(options, ""))
        {
        }

        private GroupAccess(string name, Input<string> id, GroupAccessState? state = null, CustomResourceOptions? options = null)
            : base("temporalcloud:index/groupAccess:GroupAccess", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/Grip-Security/pulumi-temporalcloud/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing GroupAccess resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static GroupAccess Get(string name, Input<string> id, GroupAccessState? state = null, CustomResourceOptions? options = null)
        {
            return new GroupAccess(name, id, state, options);
        }
    }

    public sealed class GroupAccessArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
        /// </summary>
        [Input("accountAccess", required: true)]
        public Input<string> AccountAccess { get; set; } = null!;

        [Input("namespaceAccesses")]
        private InputList<Inputs.GroupAccessNamespaceAccessArgs>? _namespaceAccesses;

        /// <summary>
        /// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
        /// </summary>
        public InputList<Inputs.GroupAccessNamespaceAccessArgs> NamespaceAccesses
        {
            get => _namespaceAccesses ?? (_namespaceAccesses = new InputList<Inputs.GroupAccessNamespaceAccessArgs>());
            set => _namespaceAccesses = value;
        }

        public GroupAccessArgs()
        {
        }
        public static new GroupAccessArgs Empty => new GroupAccessArgs();
    }

    public sealed class GroupAccessState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
        /// </summary>
        [Input("accountAccess")]
        public Input<string>? AccountAccess { get; set; }

        [Input("namespaceAccesses")]
        private InputList<Inputs.GroupAccessNamespaceAccessGetArgs>? _namespaceAccesses;

        /// <summary>
        /// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
        /// </summary>
        public InputList<Inputs.GroupAccessNamespaceAccessGetArgs> NamespaceAccesses
        {
            get => _namespaceAccesses ?? (_namespaceAccesses = new InputList<Inputs.GroupAccessNamespaceAccessGetArgs>());
            set => _namespaceAccesses = value;
        }

        public GroupAccessState()
        {
        }
        public static new GroupAccessState Empty => new GroupAccessState();
    }
}
