// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud
{
    /// <summary>
    /// Provisions a namespace export sink.
    /// </summary>
    [TemporalcloudResourceType("temporalcloud:index/namespaceExportSink:NamespaceExportSink")]
    public partial class NamespaceExportSink : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A flag indicating whether the export sink is enabled or not.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// The GCS configuration details when destination_type is GCS.
        /// </summary>
        [Output("gcs")]
        public Output<Outputs.NamespaceExportSinkGcs?> Gcs { get; private set; } = null!;

        /// <summary>
        /// The namespace under which the sink is configured. It's needed to be in the format of \n\n.\n\n
        /// </summary>
        [Output("namespace")]
        public Output<string> Namespace { get; private set; } = null!;

        /// <summary>
        /// The S3 configuration details when destination_type is S3.
        /// </summary>
        [Output("s3")]
        public Output<Outputs.NamespaceExportSinkS3?> S3 { get; private set; } = null!;

        /// <summary>
        /// The unique name of the export sink, it can't be changed once set.
        /// </summary>
        [Output("sinkName")]
        public Output<string> SinkName { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.NamespaceExportSinkTimeouts?> Timeouts { get; private set; } = null!;


        /// <summary>
        /// Create a NamespaceExportSink resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NamespaceExportSink(string name, NamespaceExportSinkArgs args, CustomResourceOptions? options = null)
            : base("temporalcloud:index/namespaceExportSink:NamespaceExportSink", name, args ?? new NamespaceExportSinkArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NamespaceExportSink(string name, Input<string> id, NamespaceExportSinkState? state = null, CustomResourceOptions? options = null)
            : base("temporalcloud:index/namespaceExportSink:NamespaceExportSink", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/Grip-Security/pulumi-temporalcloud/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NamespaceExportSink resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NamespaceExportSink Get(string name, Input<string> id, NamespaceExportSinkState? state = null, CustomResourceOptions? options = null)
        {
            return new NamespaceExportSink(name, id, state, options);
        }
    }

    public sealed class NamespaceExportSinkArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A flag indicating whether the export sink is enabled or not.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The GCS configuration details when destination_type is GCS.
        /// </summary>
        [Input("gcs")]
        public Input<Inputs.NamespaceExportSinkGcsArgs>? Gcs { get; set; }

        /// <summary>
        /// The namespace under which the sink is configured. It's needed to be in the format of \n\n.\n\n
        /// </summary>
        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        /// <summary>
        /// The S3 configuration details when destination_type is S3.
        /// </summary>
        [Input("s3")]
        public Input<Inputs.NamespaceExportSinkS3Args>? S3 { get; set; }

        /// <summary>
        /// The unique name of the export sink, it can't be changed once set.
        /// </summary>
        [Input("sinkName", required: true)]
        public Input<string> SinkName { get; set; } = null!;

        [Input("timeouts")]
        public Input<Inputs.NamespaceExportSinkTimeoutsArgs>? Timeouts { get; set; }

        public NamespaceExportSinkArgs()
        {
        }
        public static new NamespaceExportSinkArgs Empty => new NamespaceExportSinkArgs();
    }

    public sealed class NamespaceExportSinkState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A flag indicating whether the export sink is enabled or not.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The GCS configuration details when destination_type is GCS.
        /// </summary>
        [Input("gcs")]
        public Input<Inputs.NamespaceExportSinkGcsGetArgs>? Gcs { get; set; }

        /// <summary>
        /// The namespace under which the sink is configured. It's needed to be in the format of \n\n.\n\n
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// The S3 configuration details when destination_type is S3.
        /// </summary>
        [Input("s3")]
        public Input<Inputs.NamespaceExportSinkS3GetArgs>? S3 { get; set; }

        /// <summary>
        /// The unique name of the export sink, it can't be changed once set.
        /// </summary>
        [Input("sinkName")]
        public Input<string>? SinkName { get; set; }

        [Input("timeouts")]
        public Input<Inputs.NamespaceExportSinkTimeoutsGetArgs>? Timeouts { get; set; }

        public NamespaceExportSinkState()
        {
        }
        public static new NamespaceExportSinkState Empty => new NamespaceExportSinkState();
    }
}
