// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud
{
    /// <summary>
    /// Provisions a Temporal Cloud Service Account.
    /// 
    /// ## Import
    /// 
    /// Service Accounts can be imported to incorporate existing Service Accounts into your Terraform pipeline.
    /// 
    /// To import a Service Account, you need
    /// 
    /// - a resource configuration in your Terraform configuration file/module to accept the imported Service Account. In the example below, the placeholder is "temporalcloud_service_account" "saimport"
    /// 
    /// - the Service Accounts's ID, which is found using the Temporal Cloud CLI tcld sa l. In the example below, this is e3cb94fbdbb845f480044d053d00665b
    /// 
    /// ```sh
    /// $ pulumi import temporalcloud:index/serviceAccount:ServiceAccount saimport e3cb94fbdbb845f480044d053d00665b
    /// ```
    /// </summary>
    [TemporalcloudResourceType("temporalcloud:index/serviceAccount:ServiceAccount")]
    public partial class ServiceAccount : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The role on the account. Must be one of admin, developer, or read (case-insensitive).
        /// </summary>
        [Output("accountAccess")]
        public Output<string> AccountAccess { get; private set; } = null!;

        /// <summary>
        /// The name associated with the service account.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Service Accounts with an account*access role of admin cannot be assigned explicit permissions to namespaces. Admins implicitly receive access to all Namespaces.
        /// </summary>
        [Output("namespaceAccesses")]
        public Output<ImmutableArray<Outputs.ServiceAccountNamespaceAccess>> NamespaceAccesses { get; private set; } = null!;

        /// <summary>
        /// The current state of the Service Account.
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.ServiceAccountTimeouts?> Timeouts { get; private set; } = null!;


        /// <summary>
        /// Create a ServiceAccount resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServiceAccount(string name, ServiceAccountArgs args, CustomResourceOptions? options = null)
            : base("temporalcloud:index/serviceAccount:ServiceAccount", name, args ?? new ServiceAccountArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ServiceAccount(string name, Input<string> id, ServiceAccountState? state = null, CustomResourceOptions? options = null)
            : base("temporalcloud:index/serviceAccount:ServiceAccount", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServiceAccount resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServiceAccount Get(string name, Input<string> id, ServiceAccountState? state = null, CustomResourceOptions? options = null)
        {
            return new ServiceAccount(name, id, state, options);
        }
    }

    public sealed class ServiceAccountArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The role on the account. Must be one of admin, developer, or read (case-insensitive).
        /// </summary>
        [Input("accountAccess", required: true)]
        public Input<string> AccountAccess { get; set; } = null!;

        /// <summary>
        /// The name associated with the service account.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("namespaceAccesses")]
        private InputList<Inputs.ServiceAccountNamespaceAccessArgs>? _namespaceAccesses;

        /// <summary>
        /// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Service Accounts with an account*access role of admin cannot be assigned explicit permissions to namespaces. Admins implicitly receive access to all Namespaces.
        /// </summary>
        public InputList<Inputs.ServiceAccountNamespaceAccessArgs> NamespaceAccesses
        {
            get => _namespaceAccesses ?? (_namespaceAccesses = new InputList<Inputs.ServiceAccountNamespaceAccessArgs>());
            set => _namespaceAccesses = value;
        }

        [Input("timeouts")]
        public Input<Inputs.ServiceAccountTimeoutsArgs>? Timeouts { get; set; }

        public ServiceAccountArgs()
        {
        }
        public static new ServiceAccountArgs Empty => new ServiceAccountArgs();
    }

    public sealed class ServiceAccountState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The role on the account. Must be one of admin, developer, or read (case-insensitive).
        /// </summary>
        [Input("accountAccess")]
        public Input<string>? AccountAccess { get; set; }

        /// <summary>
        /// The name associated with the service account.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("namespaceAccesses")]
        private InputList<Inputs.ServiceAccountNamespaceAccessGetArgs>? _namespaceAccesses;

        /// <summary>
        /// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Service Accounts with an account*access role of admin cannot be assigned explicit permissions to namespaces. Admins implicitly receive access to all Namespaces.
        /// </summary>
        public InputList<Inputs.ServiceAccountNamespaceAccessGetArgs> NamespaceAccesses
        {
            get => _namespaceAccesses ?? (_namespaceAccesses = new InputList<Inputs.ServiceAccountNamespaceAccessGetArgs>());
            set => _namespaceAccesses = value;
        }

        /// <summary>
        /// The current state of the Service Account.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("timeouts")]
        public Input<Inputs.ServiceAccountTimeoutsGetArgs>? Timeouts { get; set; }

        public ServiceAccountState()
        {
        }
        public static new ServiceAccountState Empty => new ServiceAccountState();
    }
}
