// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// If set to True, it allows for an insecure connection to the Temporal Cloud API. This should never be set to 'true' in
// production and defaults to false.
func GetAllowInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "temporalcloud:allowInsecure")
}

// The API key for Temporal Cloud. See [this documentation](https://docs.temporal.io/cloud/api-keys) for information on how
// to obtain an API key.
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "temporalcloud:apiKey")
}

// The endpoint for the Temporal Cloud API. Defaults to `saas-api.tmprl.cloud:443`.
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "temporalcloud:endpoint")
}
