// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.PulumiTemporalCloud.Outputs
{

    [OutputType]
    public sealed class GetNamespacesNamespaceCertificateFilterResult
    {
        /// <summary>
        /// The certificate's common name.
        /// </summary>
        public readonly string CommonName;
        /// <summary>
        /// The certificate's organization.
        /// </summary>
        public readonly string Organization;
        /// <summary>
        /// The certificate's organizational unit.
        /// </summary>
        public readonly string OrganizationalUnit;
        /// <summary>
        /// The certificate's subject alternative name (or SAN).
        /// </summary>
        public readonly string SubjectAlternativeName;

        [OutputConstructor]
        private GetNamespacesNamespaceCertificateFilterResult(
            string commonName,

            string organization,

            string organizationalUnit,

            string subjectAlternativeName)
        {
            CommonName = commonName;
            Organization = organization;
            OrganizationalUnit = organizationalUnit;
            SubjectAlternativeName = subjectAlternativeName;
        }
    }
}
