// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Outputs
{

    [OutputType]
    public sealed class GetNexusEndpointsNexusEndpointResult
    {
        /// <summary>
        /// Namespace Id(s) that are allowed to call this Endpoint.
        /// </summary>
        public readonly ImmutableArray<string> AllowedCallerNamespaces;
        /// <summary>
        /// The creation time of the Nexus Endpoint.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The description of the Nexus Endpoint.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The unique identifier of the Nexus Endpoint.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the endpoint. Unique within an account and match `^[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9]$`
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The current state of the Nexus Endpoint.
        /// </summary>
        public readonly string State;
        /// <summary>
        /// The last update time of the Nexus Endpoint.
        /// </summary>
        public readonly string UpdatedAt;
        /// <summary>
        /// The target spec for routing nexus requests to a specific cloud namespace worker.
        /// </summary>
        public readonly Outputs.GetNexusEndpointsNexusEndpointWorkerTargetResult WorkerTarget;

        [OutputConstructor]
        private GetNexusEndpointsNexusEndpointResult(
            ImmutableArray<string> allowedCallerNamespaces,

            string createdAt,

            string description,

            string id,

            string name,

            string state,

            string updatedAt,

            Outputs.GetNexusEndpointsNexusEndpointWorkerTargetResult workerTarget)
        {
            AllowedCallerNamespaces = allowedCallerNamespaces;
            CreatedAt = createdAt;
            Description = description;
            Id = id;
            Name = name;
            State = state;
            UpdatedAt = updatedAt;
            WorkerTarget = workerTarget;
        }
    }
}
