// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Outputs
{

    [OutputType]
    public sealed class GetNexusEndpointsNexusEndpointWorkerTargetResult
    {
        /// <summary>
        /// The target cloud namespace to route requests to. Namespace is in same account as the endpoint.
        /// </summary>
        public readonly string NamespaceId;
        /// <summary>
        /// The task queue on the cloud namespace to route requests to.
        /// </summary>
        public readonly string TaskQueue;

        [OutputConstructor]
        private GetNexusEndpointsNexusEndpointWorkerTargetResult(
            string namespaceId,

            string taskQueue)
        {
            NamespaceId = namespaceId;
            TaskQueue = taskQueue;
        }
    }
}
