// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Temporalcloud.Outputs
{

    [OutputType]
    public sealed class GetNamespacesNamespaceLimitsResult
    {
        /// <summary>
        /// The number of actions per second (APS) that is currently allowed for the namespace. The namespace may be throttled if its APS exceeds the limit.
        /// </summary>
        public readonly int ActionsPerSecondLimit;

        [OutputConstructor]
        private GetNamespacesNamespaceLimitsResult(int actionsPerSecondLimit)
        {
            ActionsPerSecondLimit = actionsPerSecondLimit;
        }
    }
}
