// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.PulumiTemporalCloud.Outputs
{

    [OutputType]
    public sealed class GetRegionsRegionResult
    {
        /// <summary>
        /// The name of the Cloud provider for this region, e.g. `aws`.
        /// </summary>
        public readonly string CloudProvider;
        /// <summary>
        /// The name of the region within the Cloud provider, e.g. `us-east-1`.
        /// </summary>
        public readonly string CloudProviderRegion;
        /// <summary>
        /// The unique identifier for the region, e.g. `aws-us-east-1`.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The physical location of the region, e.g. "US East (N. Virginia)".
        /// </summary>
        public readonly string Location;

        [OutputConstructor]
        private GetRegionsRegionResult(
            string cloudProvider,

            string cloudProviderRegion,

            string id,

            string location)
        {
            CloudProvider = cloudProvider;
            CloudProviderRegion = cloudProviderRegion;
            Id = id;
            Location = location;
        }
    }
}
