// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Temporalcloud.Outputs
{

    [OutputType]
    public sealed class GetServiceAccountsServiceAccountResult
    {
        /// <summary>
        /// The role on the account. Must be one of admin, developer, or read (case-insensitive).
        /// </summary>
        public readonly string AccountAccess;
        /// <summary>
        /// The creation time of the Service Account.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The description of the Service Account.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The unique identifier of the Service Account.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name associated with the service account.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The set of namespace permissions for this service account, including each namespace and its role.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetServiceAccountsServiceAccountNamespaceAccessResult> NamespaceAccesses;
        /// <summary>
        /// The current state of the Service Account.
        /// </summary>
        public readonly string State;
        /// <summary>
        /// The last update time of the Service Account.
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetServiceAccountsServiceAccountResult(
            string accountAccess,

            string createdAt,

            string description,

            string id,

            string name,

            ImmutableArray<Outputs.GetServiceAccountsServiceAccountNamespaceAccessResult> namespaceAccesses,

            string state,

            string updatedAt)
        {
            AccountAccess = accountAccess;
            CreatedAt = createdAt;
            Description = description;
            Id = id;
            Name = name;
            NamespaceAccesses = namespaceAccesses;
            State = state;
            UpdatedAt = updatedAt;
        }
    }
}
