// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Outputs
{

    [OutputType]
    public sealed class NamespaceExportSinkS3
    {
        /// <summary>
        /// The AWS account ID associated with the S3 bucket and the assumed role.
        /// </summary>
        public readonly string AwsAccountId;
        /// <summary>
        /// The name of the destination S3 bucket where Temporal will send data.
        /// </summary>
        public readonly string BucketName;
        /// <summary>
        /// The AWS Key Management Service (KMS) ARN used for encryption.
        /// </summary>
        public readonly string KmsArn;
        /// <summary>
        /// The region where the S3 bucket is located.
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// The IAM role that Temporal Cloud assumes for writing records to the customer's S3 bucket.
        /// </summary>
        public readonly string RoleName;

        [OutputConstructor]
        private NamespaceExportSinkS3(
            string awsAccountId,

            string bucketName,

            string kmsArn,

            string region,

            string roleName)
        {
            AwsAccountId = awsAccountId;
            BucketName = bucketName;
            KmsArn = kmsArn;
            Region = region;
            RoleName = roleName;
        }
    }
}
