// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Outputs
{

    [OutputType]
    public sealed class NamespaceExportSinkGcs
    {
        /// <summary>
        /// The name of the destination GCS bucket where Temporal will send data.
        /// </summary>
        public readonly string BucketName;
        /// <summary>
        /// The GCP project ID associated with the GCS bucket and service account.
        /// </summary>
        public readonly string GcpProjectId;
        /// <summary>
        /// The region of the gcs bucket
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// The customer service account ID that Temporal Cloud impersonates for writing records to the customer's GCS bucket.
        /// </summary>
        public readonly string ServiceAccountId;

        [OutputConstructor]
        private NamespaceExportSinkGcs(
            string bucketName,

            string gcpProjectId,

            string region,

            string serviceAccountId)
        {
            BucketName = bucketName;
            GcpProjectId = gcpProjectId;
            Region = region;
            ServiceAccountId = serviceAccountId;
        }
    }
}
