// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Outputs
{

    [OutputType]
    public sealed class NamespaceExportSinkGcs
    {
        /// <summary>
        /// The name of the destination GCS bucket where Temporal will send data.
        /// </summary>
        public readonly string BucketName;
        /// <summary>
        /// The GCP project ID associated with the GCS bucket and service account. If not provided, the service*account*email must be provided.
        /// </summary>
        public readonly string? GcpProjectId;
        /// <summary>
        /// The region of the gcs bucket
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// The service account email associated with the GCS bucket and service account. If not provided, the service*account*id and gcp*project*id must be provided.
        /// </summary>
        public readonly string? ServiceAccountEmail;
        /// <summary>
        /// The customer service account ID that Temporal Cloud impersonates for writing records to the customer's GCS bucket. If not provided, the service*account*email must be provided.
        /// </summary>
        public readonly string? ServiceAccountId;

        [OutputConstructor]
        private NamespaceExportSinkGcs(
            string bucketName,

            string? gcpProjectId,

            string region,

            string? serviceAccountEmail,

            string? serviceAccountId)
        {
            BucketName = bucketName;
            GcpProjectId = gcpProjectId;
            Region = region;
            ServiceAccountEmail = serviceAccountEmail;
            ServiceAccountId = serviceAccountId;
        }
    }
}
