// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Outputs
{

    [OutputType]
    public sealed class NexusEndpointWorkerTarget
    {
        /// <summary>
        /// The target cloud namespace to route requests to. Namespace must be in same account as the endpoint.
        /// </summary>
        public readonly string NamespaceId;
        /// <summary>
        /// The task queue on the cloud namespace to route requests to.
        /// </summary>
        public readonly string TaskQueue;

        [OutputConstructor]
        private NexusEndpointWorkerTarget(
            string namespaceId,

            string taskQueue)
        {
            NamespaceId = namespaceId;
            TaskQueue = taskQueue;
        }
    }
}
