// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package temporalcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provisions a Temporal Cloud Connectivity Rule.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Create Public Connectivity Rule
//			_, err := temporalcloud.NewConnectivityRule(ctx, "public_rule", &temporalcloud.ConnectivityRuleArgs{
//				ConnectivityType: pulumi.String("public"),
//			})
//			if err != nil {
//				return err
//			}
//			// Create Private Connectivity Rule for AWS
//			_, err = temporalcloud.NewConnectivityRule(ctx, "private_aws", &temporalcloud.ConnectivityRuleArgs{
//				ConnectivityType: pulumi.String("private"),
//				ConnectionId:     pulumi.String("vpce-12345678"),
//				Region:           pulumi.String("aws-us-west-2"),
//			})
//			if err != nil {
//				return err
//			}
//			// Create Private Connectivity Rule for GCP
//			_, err = temporalcloud.NewConnectivityRule(ctx, "private_gcp", &temporalcloud.ConnectivityRuleArgs{
//				ConnectivityType: pulumi.String("private"),
//				ConnectionId:     pulumi.String("vpce-12345678"),
//				Region:           pulumi.String("gcp-us-central1"),
//				GcpProjectId:     pulumi.String("my-gcp-project-id"),
//			})
//			if err != nil {
//				return err
//			}
//			// Attaching connectivity rules to a namespace
//			_, err = temporalcloud.NewNamespace(ctx, "ns-with-cr", &temporalcloud.NamespaceArgs{
//				Name: pulumi.String("ns-with-cr"),
//				Regions: pulumi.StringArray{
//					pulumi.String("aws-us-west-2"),
//				},
//				ApiKeyAuth:    pulumi.Bool(true),
//				RetentionDays: pulumi.Int(14),
//				ConnectivityRuleIds: pulumi.StringArray{
//					id,
//					idPrivateAws,
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type ConnectivityRule struct {
	pulumi.CustomResourceState

	// The connection ID of the private connection.
	ConnectionId pulumi.StringPtrOutput `pulumi:"connectionId"`
	// The type of connectivity. Must be one of 'public' or 'private'.
	ConnectivityType pulumi.StringOutput `pulumi:"connectivityType"`
	// The GCP project ID. Required when cloudProvider is 'gcp'.
	GcpProjectId pulumi.StringPtrOutput `pulumi:"gcpProjectId"`
	// The region of the connection. Example: 'aws-us-west-2'.
	Region   pulumi.StringPtrOutput            `pulumi:"region"`
	Timeouts ConnectivityRuleTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewConnectivityRule registers a new resource with the given unique name, arguments, and options.
func NewConnectivityRule(ctx *pulumi.Context,
	name string, args *ConnectivityRuleArgs, opts ...pulumi.ResourceOption) (*ConnectivityRule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConnectivityType == nil {
		return nil, errors.New("invalid value for required argument 'ConnectivityType'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ConnectivityRule
	err := ctx.RegisterResource("temporalcloud:index/connectivityRule:ConnectivityRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetConnectivityRule gets an existing ConnectivityRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetConnectivityRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ConnectivityRuleState, opts ...pulumi.ResourceOption) (*ConnectivityRule, error) {
	var resource ConnectivityRule
	err := ctx.ReadResource("temporalcloud:index/connectivityRule:ConnectivityRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ConnectivityRule resources.
type connectivityRuleState struct {
	// The connection ID of the private connection.
	ConnectionId *string `pulumi:"connectionId"`
	// The type of connectivity. Must be one of 'public' or 'private'.
	ConnectivityType *string `pulumi:"connectivityType"`
	// The GCP project ID. Required when cloudProvider is 'gcp'.
	GcpProjectId *string `pulumi:"gcpProjectId"`
	// The region of the connection. Example: 'aws-us-west-2'.
	Region   *string                   `pulumi:"region"`
	Timeouts *ConnectivityRuleTimeouts `pulumi:"timeouts"`
}

type ConnectivityRuleState struct {
	// The connection ID of the private connection.
	ConnectionId pulumi.StringPtrInput
	// The type of connectivity. Must be one of 'public' or 'private'.
	ConnectivityType pulumi.StringPtrInput
	// The GCP project ID. Required when cloudProvider is 'gcp'.
	GcpProjectId pulumi.StringPtrInput
	// The region of the connection. Example: 'aws-us-west-2'.
	Region   pulumi.StringPtrInput
	Timeouts ConnectivityRuleTimeoutsPtrInput
}

func (ConnectivityRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*connectivityRuleState)(nil)).Elem()
}

type connectivityRuleArgs struct {
	// The connection ID of the private connection.
	ConnectionId *string `pulumi:"connectionId"`
	// The type of connectivity. Must be one of 'public' or 'private'.
	ConnectivityType string `pulumi:"connectivityType"`
	// The GCP project ID. Required when cloudProvider is 'gcp'.
	GcpProjectId *string `pulumi:"gcpProjectId"`
	// The region of the connection. Example: 'aws-us-west-2'.
	Region   *string                   `pulumi:"region"`
	Timeouts *ConnectivityRuleTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a ConnectivityRule resource.
type ConnectivityRuleArgs struct {
	// The connection ID of the private connection.
	ConnectionId pulumi.StringPtrInput
	// The type of connectivity. Must be one of 'public' or 'private'.
	ConnectivityType pulumi.StringInput
	// The GCP project ID. Required when cloudProvider is 'gcp'.
	GcpProjectId pulumi.StringPtrInput
	// The region of the connection. Example: 'aws-us-west-2'.
	Region   pulumi.StringPtrInput
	Timeouts ConnectivityRuleTimeoutsPtrInput
}

func (ConnectivityRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*connectivityRuleArgs)(nil)).Elem()
}

type ConnectivityRuleInput interface {
	pulumi.Input

	ToConnectivityRuleOutput() ConnectivityRuleOutput
	ToConnectivityRuleOutputWithContext(ctx context.Context) ConnectivityRuleOutput
}

func (*ConnectivityRule) ElementType() reflect.Type {
	return reflect.TypeOf((**ConnectivityRule)(nil)).Elem()
}

func (i *ConnectivityRule) ToConnectivityRuleOutput() ConnectivityRuleOutput {
	return i.ToConnectivityRuleOutputWithContext(context.Background())
}

func (i *ConnectivityRule) ToConnectivityRuleOutputWithContext(ctx context.Context) ConnectivityRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConnectivityRuleOutput)
}

// ConnectivityRuleArrayInput is an input type that accepts ConnectivityRuleArray and ConnectivityRuleArrayOutput values.
// You can construct a concrete instance of `ConnectivityRuleArrayInput` via:
//
//	ConnectivityRuleArray{ ConnectivityRuleArgs{...} }
type ConnectivityRuleArrayInput interface {
	pulumi.Input

	ToConnectivityRuleArrayOutput() ConnectivityRuleArrayOutput
	ToConnectivityRuleArrayOutputWithContext(context.Context) ConnectivityRuleArrayOutput
}

type ConnectivityRuleArray []ConnectivityRuleInput

func (ConnectivityRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ConnectivityRule)(nil)).Elem()
}

func (i ConnectivityRuleArray) ToConnectivityRuleArrayOutput() ConnectivityRuleArrayOutput {
	return i.ToConnectivityRuleArrayOutputWithContext(context.Background())
}

func (i ConnectivityRuleArray) ToConnectivityRuleArrayOutputWithContext(ctx context.Context) ConnectivityRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConnectivityRuleArrayOutput)
}

// ConnectivityRuleMapInput is an input type that accepts ConnectivityRuleMap and ConnectivityRuleMapOutput values.
// You can construct a concrete instance of `ConnectivityRuleMapInput` via:
//
//	ConnectivityRuleMap{ "key": ConnectivityRuleArgs{...} }
type ConnectivityRuleMapInput interface {
	pulumi.Input

	ToConnectivityRuleMapOutput() ConnectivityRuleMapOutput
	ToConnectivityRuleMapOutputWithContext(context.Context) ConnectivityRuleMapOutput
}

type ConnectivityRuleMap map[string]ConnectivityRuleInput

func (ConnectivityRuleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ConnectivityRule)(nil)).Elem()
}

func (i ConnectivityRuleMap) ToConnectivityRuleMapOutput() ConnectivityRuleMapOutput {
	return i.ToConnectivityRuleMapOutputWithContext(context.Background())
}

func (i ConnectivityRuleMap) ToConnectivityRuleMapOutputWithContext(ctx context.Context) ConnectivityRuleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConnectivityRuleMapOutput)
}

type ConnectivityRuleOutput struct{ *pulumi.OutputState }

func (ConnectivityRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ConnectivityRule)(nil)).Elem()
}

func (o ConnectivityRuleOutput) ToConnectivityRuleOutput() ConnectivityRuleOutput {
	return o
}

func (o ConnectivityRuleOutput) ToConnectivityRuleOutputWithContext(ctx context.Context) ConnectivityRuleOutput {
	return o
}

// The connection ID of the private connection.
func (o ConnectivityRuleOutput) ConnectionId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ConnectivityRule) pulumi.StringPtrOutput { return v.ConnectionId }).(pulumi.StringPtrOutput)
}

// The type of connectivity. Must be one of 'public' or 'private'.
func (o ConnectivityRuleOutput) ConnectivityType() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectivityRule) pulumi.StringOutput { return v.ConnectivityType }).(pulumi.StringOutput)
}

// The GCP project ID. Required when cloudProvider is 'gcp'.
func (o ConnectivityRuleOutput) GcpProjectId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ConnectivityRule) pulumi.StringPtrOutput { return v.GcpProjectId }).(pulumi.StringPtrOutput)
}

// The region of the connection. Example: 'aws-us-west-2'.
func (o ConnectivityRuleOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ConnectivityRule) pulumi.StringPtrOutput { return v.Region }).(pulumi.StringPtrOutput)
}

func (o ConnectivityRuleOutput) Timeouts() ConnectivityRuleTimeoutsPtrOutput {
	return o.ApplyT(func(v *ConnectivityRule) ConnectivityRuleTimeoutsPtrOutput { return v.Timeouts }).(ConnectivityRuleTimeoutsPtrOutput)
}

type ConnectivityRuleArrayOutput struct{ *pulumi.OutputState }

func (ConnectivityRuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ConnectivityRule)(nil)).Elem()
}

func (o ConnectivityRuleArrayOutput) ToConnectivityRuleArrayOutput() ConnectivityRuleArrayOutput {
	return o
}

func (o ConnectivityRuleArrayOutput) ToConnectivityRuleArrayOutputWithContext(ctx context.Context) ConnectivityRuleArrayOutput {
	return o
}

func (o ConnectivityRuleArrayOutput) Index(i pulumi.IntInput) ConnectivityRuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ConnectivityRule {
		return vs[0].([]*ConnectivityRule)[vs[1].(int)]
	}).(ConnectivityRuleOutput)
}

type ConnectivityRuleMapOutput struct{ *pulumi.OutputState }

func (ConnectivityRuleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ConnectivityRule)(nil)).Elem()
}

func (o ConnectivityRuleMapOutput) ToConnectivityRuleMapOutput() ConnectivityRuleMapOutput {
	return o
}

func (o ConnectivityRuleMapOutput) ToConnectivityRuleMapOutputWithContext(ctx context.Context) ConnectivityRuleMapOutput {
	return o
}

func (o ConnectivityRuleMapOutput) MapIndex(k pulumi.StringInput) ConnectivityRuleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ConnectivityRule {
		return vs[0].(map[string]*ConnectivityRule)[vs[1].(string)]
	}).(ConnectivityRuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ConnectivityRuleInput)(nil)).Elem(), &ConnectivityRule{})
	pulumi.RegisterInputType(reflect.TypeOf((*ConnectivityRuleArrayInput)(nil)).Elem(), ConnectivityRuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ConnectivityRuleMapInput)(nil)).Elem(), ConnectivityRuleMap{})
	pulumi.RegisterOutputType(ConnectivityRuleOutput{})
	pulumi.RegisterOutputType(ConnectivityRuleArrayOutput{})
	pulumi.RegisterOutputType(ConnectivityRuleMapOutput{})
}
