// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package temporalcloud

import (
	"context"
	"reflect"

	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Fetches details about a connectivity rule.
func LookupConnectivityRule(ctx *pulumi.Context, args *LookupConnectivityRuleArgs, opts ...pulumi.InvokeOption) (*LookupConnectivityRuleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupConnectivityRuleResult
	err := ctx.Invoke("temporalcloud:index/getConnectivityRule:getConnectivityRule", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getConnectivityRule.
type LookupConnectivityRuleArgs struct {
	// The unique identifier of the connectivity rule across all Temporal Cloud tenants.
	Id string `pulumi:"id"`
}

// A collection of values returned by getConnectivityRule.
type LookupConnectivityRuleResult struct {
	// The ID of the connection to the connectivity rule.
	ConnectionId string `pulumi:"connectionId"`
	// The type of connectivity.
	ConnectivityType string `pulumi:"connectivityType"`
	// The time the connectivity rule was created.
	CreatedAt string `pulumi:"createdAt"`
	// The GCP project ID of the connectivity rule.
	GcpProjectId string `pulumi:"gcpProjectId"`
	// The unique identifier of the connectivity rule across all Temporal Cloud tenants.
	Id string `pulumi:"id"`
	// The region of the connectivity rule.
	Region string `pulumi:"region"`
	// The current state of the connectivity rule.
	State string `pulumi:"state"`
}

func LookupConnectivityRuleOutput(ctx *pulumi.Context, args LookupConnectivityRuleOutputArgs, opts ...pulumi.InvokeOption) LookupConnectivityRuleResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupConnectivityRuleResultOutput, error) {
			args := v.(LookupConnectivityRuleArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("temporalcloud:index/getConnectivityRule:getConnectivityRule", args, LookupConnectivityRuleResultOutput{}, options).(LookupConnectivityRuleResultOutput), nil
		}).(LookupConnectivityRuleResultOutput)
}

// A collection of arguments for invoking getConnectivityRule.
type LookupConnectivityRuleOutputArgs struct {
	// The unique identifier of the connectivity rule across all Temporal Cloud tenants.
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupConnectivityRuleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupConnectivityRuleArgs)(nil)).Elem()
}

// A collection of values returned by getConnectivityRule.
type LookupConnectivityRuleResultOutput struct{ *pulumi.OutputState }

func (LookupConnectivityRuleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupConnectivityRuleResult)(nil)).Elem()
}

func (o LookupConnectivityRuleResultOutput) ToLookupConnectivityRuleResultOutput() LookupConnectivityRuleResultOutput {
	return o
}

func (o LookupConnectivityRuleResultOutput) ToLookupConnectivityRuleResultOutputWithContext(ctx context.Context) LookupConnectivityRuleResultOutput {
	return o
}

// The ID of the connection to the connectivity rule.
func (o LookupConnectivityRuleResultOutput) ConnectionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectivityRuleResult) string { return v.ConnectionId }).(pulumi.StringOutput)
}

// The type of connectivity.
func (o LookupConnectivityRuleResultOutput) ConnectivityType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectivityRuleResult) string { return v.ConnectivityType }).(pulumi.StringOutput)
}

// The time the connectivity rule was created.
func (o LookupConnectivityRuleResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectivityRuleResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The GCP project ID of the connectivity rule.
func (o LookupConnectivityRuleResultOutput) GcpProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectivityRuleResult) string { return v.GcpProjectId }).(pulumi.StringOutput)
}

// The unique identifier of the connectivity rule across all Temporal Cloud tenants.
func (o LookupConnectivityRuleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectivityRuleResult) string { return v.Id }).(pulumi.StringOutput)
}

// The region of the connectivity rule.
func (o LookupConnectivityRuleResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectivityRuleResult) string { return v.Region }).(pulumi.StringOutput)
}

// The current state of the connectivity rule.
func (o LookupConnectivityRuleResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConnectivityRuleResult) string { return v.State }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupConnectivityRuleResultOutput{})
}
