// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package temporalcloud

import (
	"context"
	"reflect"

	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Fetches details about all Nexus Endpoints.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			myNexusEndpoints, err := temporalcloud.GetNexusEndpoints(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("nexusEndpoints", myNexusEndpoints.NexusEndpoints)
//			return nil
//		})
//	}
//
// ```
func GetNexusEndpoints(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetNexusEndpointsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetNexusEndpointsResult
	err := ctx.Invoke("temporalcloud:index/getNexusEndpoints:getNexusEndpoints", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getNexusEndpoints.
type GetNexusEndpointsResult struct {
	// The unique identifier of the Nexus Endpoints data source.
	Id string `pulumi:"id"`
	// The list of Nexus Endpoints.
	NexusEndpoints []GetNexusEndpointsNexusEndpoint `pulumi:"nexusEndpoints"`
}

func GetNexusEndpointsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetNexusEndpointsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetNexusEndpointsResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("temporalcloud:index/getNexusEndpoints:getNexusEndpoints", nil, GetNexusEndpointsResultOutput{}, options).(GetNexusEndpointsResultOutput), nil
	}).(GetNexusEndpointsResultOutput)
}

// A collection of values returned by getNexusEndpoints.
type GetNexusEndpointsResultOutput struct{ *pulumi.OutputState }

func (GetNexusEndpointsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNexusEndpointsResult)(nil)).Elem()
}

func (o GetNexusEndpointsResultOutput) ToGetNexusEndpointsResultOutput() GetNexusEndpointsResultOutput {
	return o
}

func (o GetNexusEndpointsResultOutput) ToGetNexusEndpointsResultOutputWithContext(ctx context.Context) GetNexusEndpointsResultOutput {
	return o
}

// The unique identifier of the Nexus Endpoints data source.
func (o GetNexusEndpointsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNexusEndpointsResult) string { return v.Id }).(pulumi.StringOutput)
}

// The list of Nexus Endpoints.
func (o GetNexusEndpointsResultOutput) NexusEndpoints() GetNexusEndpointsNexusEndpointArrayOutput {
	return o.ApplyT(func(v GetNexusEndpointsResult) []GetNexusEndpointsNexusEndpoint { return v.NexusEndpoints }).(GetNexusEndpointsNexusEndpointArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNexusEndpointsResultOutput{})
}
