// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package temporalcloud

import (
	"context"
	"reflect"

	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Fetches details about a Namespace.
func LookupNamespace(ctx *pulumi.Context, args *LookupNamespaceArgs, opts ...pulumi.InvokeOption) (*LookupNamespaceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNamespaceResult
	err := ctx.Invoke("temporalcloud:index/getNamespace:getNamespace", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNamespace.
type LookupNamespaceArgs struct {
	// If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
	ApiKeyAuth *bool `pulumi:"apiKeyAuth"`
	// A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
	CertificateFilters []GetNamespaceCertificateFilter `pulumi:"certificateFilters"`
	// A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
	CodecServer *GetNamespaceCodecServer `pulumi:"codecServer"`
	// The IDs of the connectivity rules for this namespace.
	ConnectivityRuleIds []string `pulumi:"connectivityRuleIds"`
	// The custom search attributes to use for the namespace.
	CustomSearchAttributes map[string]string `pulumi:"customSearchAttributes"`
	// The unique identifier of the namespace across all Temporal Cloud tenants.
	Id string `pulumi:"id"`
	// The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
	LastModifiedTime *string `pulumi:"lastModifiedTime"`
	// The private connectivities for the namespace, if any.
	PrivateConnectivities []GetNamespacePrivateConnectivity `pulumi:"privateConnectivities"`
}

// A collection of values returned by getNamespace.
type LookupNamespaceResult struct {
	// The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud.
	AcceptedClientCa string `pulumi:"acceptedClientCa"`
	// The currently active region for the namespace.
	ActiveRegion string `pulumi:"activeRegion"`
	// If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
	ApiKeyAuth *bool `pulumi:"apiKeyAuth"`
	// A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
	CertificateFilters []GetNamespaceCertificateFilter `pulumi:"certificateFilters"`
	// A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
	CodecServer GetNamespaceCodecServer `pulumi:"codecServer"`
	// The IDs of the connectivity rules for this namespace.
	ConnectivityRuleIds []string `pulumi:"connectivityRuleIds"`
	// The date and time when the namespace was created.
	CreatedTime string `pulumi:"createdTime"`
	// The custom search attributes to use for the namespace.
	CustomSearchAttributes map[string]string `pulumi:"customSearchAttributes"`
	// The endpoints for the namespace.
	Endpoints GetNamespaceEndpoints `pulumi:"endpoints"`
	// The unique identifier of the namespace across all Temporal Cloud tenants.
	Id string `pulumi:"id"`
	// The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
	LastModifiedTime string `pulumi:"lastModifiedTime"`
	// The limits set on the namespace currently.
	Limits GetNamespaceLimits `pulumi:"limits"`
	// The name of the namespace.
	Name string `pulumi:"name"`
	// The private connectivities for the namespace, if any.
	PrivateConnectivities []GetNamespacePrivateConnectivity `pulumi:"privateConnectivities"`
	Regions               []string                          `pulumi:"regions"`
	// The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
	RetentionDays int `pulumi:"retentionDays"`
	// The current state of the namespace.
	State string `pulumi:"state"`
}

func LookupNamespaceOutput(ctx *pulumi.Context, args LookupNamespaceOutputArgs, opts ...pulumi.InvokeOption) LookupNamespaceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNamespaceResultOutput, error) {
			args := v.(LookupNamespaceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("temporalcloud:index/getNamespace:getNamespace", args, LookupNamespaceResultOutput{}, options).(LookupNamespaceResultOutput), nil
		}).(LookupNamespaceResultOutput)
}

// A collection of arguments for invoking getNamespace.
type LookupNamespaceOutputArgs struct {
	// If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
	ApiKeyAuth pulumi.BoolPtrInput `pulumi:"apiKeyAuth"`
	// A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
	CertificateFilters GetNamespaceCertificateFilterArrayInput `pulumi:"certificateFilters"`
	// A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
	CodecServer GetNamespaceCodecServerPtrInput `pulumi:"codecServer"`
	// The IDs of the connectivity rules for this namespace.
	ConnectivityRuleIds pulumi.StringArrayInput `pulumi:"connectivityRuleIds"`
	// The custom search attributes to use for the namespace.
	CustomSearchAttributes pulumi.StringMapInput `pulumi:"customSearchAttributes"`
	// The unique identifier of the namespace across all Temporal Cloud tenants.
	Id pulumi.StringInput `pulumi:"id"`
	// The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
	LastModifiedTime pulumi.StringPtrInput `pulumi:"lastModifiedTime"`
	// The private connectivities for the namespace, if any.
	PrivateConnectivities GetNamespacePrivateConnectivityArrayInput `pulumi:"privateConnectivities"`
}

func (LookupNamespaceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNamespaceArgs)(nil)).Elem()
}

// A collection of values returned by getNamespace.
type LookupNamespaceResultOutput struct{ *pulumi.OutputState }

func (LookupNamespaceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNamespaceResult)(nil)).Elem()
}

func (o LookupNamespaceResultOutput) ToLookupNamespaceResultOutput() LookupNamespaceResultOutput {
	return o
}

func (o LookupNamespaceResultOutput) ToLookupNamespaceResultOutputWithContext(ctx context.Context) LookupNamespaceResultOutput {
	return o
}

// The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud.
func (o LookupNamespaceResultOutput) AcceptedClientCa() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNamespaceResult) string { return v.AcceptedClientCa }).(pulumi.StringOutput)
}

// The currently active region for the namespace.
func (o LookupNamespaceResultOutput) ActiveRegion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNamespaceResult) string { return v.ActiveRegion }).(pulumi.StringOutput)
}

// If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
func (o LookupNamespaceResultOutput) ApiKeyAuth() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupNamespaceResult) *bool { return v.ApiKeyAuth }).(pulumi.BoolPtrOutput)
}

// A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
func (o LookupNamespaceResultOutput) CertificateFilters() GetNamespaceCertificateFilterArrayOutput {
	return o.ApplyT(func(v LookupNamespaceResult) []GetNamespaceCertificateFilter { return v.CertificateFilters }).(GetNamespaceCertificateFilterArrayOutput)
}

// A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
func (o LookupNamespaceResultOutput) CodecServer() GetNamespaceCodecServerOutput {
	return o.ApplyT(func(v LookupNamespaceResult) GetNamespaceCodecServer { return v.CodecServer }).(GetNamespaceCodecServerOutput)
}

// The IDs of the connectivity rules for this namespace.
func (o LookupNamespaceResultOutput) ConnectivityRuleIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNamespaceResult) []string { return v.ConnectivityRuleIds }).(pulumi.StringArrayOutput)
}

// The date and time when the namespace was created.
func (o LookupNamespaceResultOutput) CreatedTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNamespaceResult) string { return v.CreatedTime }).(pulumi.StringOutput)
}

// The custom search attributes to use for the namespace.
func (o LookupNamespaceResultOutput) CustomSearchAttributes() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupNamespaceResult) map[string]string { return v.CustomSearchAttributes }).(pulumi.StringMapOutput)
}

// The endpoints for the namespace.
func (o LookupNamespaceResultOutput) Endpoints() GetNamespaceEndpointsOutput {
	return o.ApplyT(func(v LookupNamespaceResult) GetNamespaceEndpoints { return v.Endpoints }).(GetNamespaceEndpointsOutput)
}

// The unique identifier of the namespace across all Temporal Cloud tenants.
func (o LookupNamespaceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNamespaceResult) string { return v.Id }).(pulumi.StringOutput)
}

// The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
func (o LookupNamespaceResultOutput) LastModifiedTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNamespaceResult) string { return v.LastModifiedTime }).(pulumi.StringOutput)
}

// The limits set on the namespace currently.
func (o LookupNamespaceResultOutput) Limits() GetNamespaceLimitsOutput {
	return o.ApplyT(func(v LookupNamespaceResult) GetNamespaceLimits { return v.Limits }).(GetNamespaceLimitsOutput)
}

// The name of the namespace.
func (o LookupNamespaceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNamespaceResult) string { return v.Name }).(pulumi.StringOutput)
}

// The private connectivities for the namespace, if any.
func (o LookupNamespaceResultOutput) PrivateConnectivities() GetNamespacePrivateConnectivityArrayOutput {
	return o.ApplyT(func(v LookupNamespaceResult) []GetNamespacePrivateConnectivity { return v.PrivateConnectivities }).(GetNamespacePrivateConnectivityArrayOutput)
}

func (o LookupNamespaceResultOutput) Regions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNamespaceResult) []string { return v.Regions }).(pulumi.StringArrayOutput)
}

// The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
func (o LookupNamespaceResultOutput) RetentionDays() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNamespaceResult) int { return v.RetentionDays }).(pulumi.IntOutput)
}

// The current state of the namespace.
func (o LookupNamespaceResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNamespaceResult) string { return v.State }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNamespaceResultOutput{})
}
