// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package temporalcloud

import (
	"context"
	"reflect"

	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Fetches details about all Service Accounts.
func GetServiceAccounts(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetServiceAccountsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetServiceAccountsResult
	err := ctx.Invoke("temporalcloud:index/getServiceAccounts:getServiceAccounts", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getServiceAccounts.
type GetServiceAccountsResult struct {
	// The unique identifier of the Service Accounts data source.
	Id string `pulumi:"id"`
	// The list of Service Accounts.
	ServiceAccounts []GetServiceAccountsServiceAccount `pulumi:"serviceAccounts"`
}

func GetServiceAccountsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetServiceAccountsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetServiceAccountsResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("temporalcloud:index/getServiceAccounts:getServiceAccounts", nil, GetServiceAccountsResultOutput{}, options).(GetServiceAccountsResultOutput), nil
	}).(GetServiceAccountsResultOutput)
}

// A collection of values returned by getServiceAccounts.
type GetServiceAccountsResultOutput struct{ *pulumi.OutputState }

func (GetServiceAccountsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServiceAccountsResult)(nil)).Elem()
}

func (o GetServiceAccountsResultOutput) ToGetServiceAccountsResultOutput() GetServiceAccountsResultOutput {
	return o
}

func (o GetServiceAccountsResultOutput) ToGetServiceAccountsResultOutputWithContext(ctx context.Context) GetServiceAccountsResultOutput {
	return o
}

// The unique identifier of the Service Accounts data source.
func (o GetServiceAccountsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetServiceAccountsResult) string { return v.Id }).(pulumi.StringOutput)
}

// The list of Service Accounts.
func (o GetServiceAccountsResultOutput) ServiceAccounts() GetServiceAccountsServiceAccountArrayOutput {
	return o.ApplyT(func(v GetServiceAccountsResult) []GetServiceAccountsServiceAccount { return v.ServiceAccounts }).(GetServiceAccountsServiceAccountArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServiceAccountsResultOutput{})
}
