// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package temporalcloud

import (
	"context"
	"reflect"

	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Fetches details about a User.
func LookupUser(ctx *pulumi.Context, args *LookupUserArgs, opts ...pulumi.InvokeOption) (*LookupUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupUserResult
	err := ctx.Invoke("temporalcloud:index/getUser:getUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUser.
type LookupUserArgs struct {
	// The unique identifier of the User.
	Id string `pulumi:"id"`
	// The set of namespace permissions for this user, including each namespace and its role.
	NamespaceAccesses []GetUserNamespaceAccess `pulumi:"namespaceAccesses"`
}

// A collection of values returned by getUser.
type LookupUserResult struct {
	// The role on the account. Must be one of admin, developer, or read (case-insensitive).
	AccountAccess string `pulumi:"accountAccess"`
	// The creation time of the User.
	CreatedAt string `pulumi:"createdAt"`
	// The email of the User.
	Email string `pulumi:"email"`
	// The unique identifier of the User.
	Id string `pulumi:"id"`
	// The set of namespace permissions for this user, including each namespace and its role.
	NamespaceAccesses []GetUserNamespaceAccess `pulumi:"namespaceAccesses"`
	// The current state of the User.
	State string `pulumi:"state"`
	// The last update time of the User.
	UpdatedAt string `pulumi:"updatedAt"`
}

func LookupUserOutput(ctx *pulumi.Context, args LookupUserOutputArgs, opts ...pulumi.InvokeOption) LookupUserResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupUserResultOutput, error) {
			args := v.(LookupUserArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("temporalcloud:index/getUser:getUser", args, LookupUserResultOutput{}, options).(LookupUserResultOutput), nil
		}).(LookupUserResultOutput)
}

// A collection of arguments for invoking getUser.
type LookupUserOutputArgs struct {
	// The unique identifier of the User.
	Id pulumi.StringInput `pulumi:"id"`
	// The set of namespace permissions for this user, including each namespace and its role.
	NamespaceAccesses GetUserNamespaceAccessArrayInput `pulumi:"namespaceAccesses"`
}

func (LookupUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserArgs)(nil)).Elem()
}

// A collection of values returned by getUser.
type LookupUserResultOutput struct{ *pulumi.OutputState }

func (LookupUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserResult)(nil)).Elem()
}

func (o LookupUserResultOutput) ToLookupUserResultOutput() LookupUserResultOutput {
	return o
}

func (o LookupUserResultOutput) ToLookupUserResultOutputWithContext(ctx context.Context) LookupUserResultOutput {
	return o
}

// The role on the account. Must be one of admin, developer, or read (case-insensitive).
func (o LookupUserResultOutput) AccountAccess() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.AccountAccess }).(pulumi.StringOutput)
}

// The creation time of the User.
func (o LookupUserResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The email of the User.
func (o LookupUserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Email }).(pulumi.StringOutput)
}

// The unique identifier of the User.
func (o LookupUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Id }).(pulumi.StringOutput)
}

// The set of namespace permissions for this user, including each namespace and its role.
func (o LookupUserResultOutput) NamespaceAccesses() GetUserNamespaceAccessArrayOutput {
	return o.ApplyT(func(v LookupUserResult) []GetUserNamespaceAccess { return v.NamespaceAccesses }).(GetUserNamespaceAccessArrayOutput)
}

// The current state of the User.
func (o LookupUserResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.State }).(pulumi.StringOutput)
}

// The last update time of the User.
func (o LookupUserResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupUserResultOutput{})
}
