// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package temporalcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provisions Temporal Cloud group access.
type GroupAccess struct {
	pulumi.CustomResourceState

	// The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
	AccountAccess pulumi.StringOutput `pulumi:"accountAccess"`
	// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
	NamespaceAccesses GroupAccessNamespaceAccessArrayOutput `pulumi:"namespaceAccesses"`
}

// NewGroupAccess registers a new resource with the given unique name, arguments, and options.
func NewGroupAccess(ctx *pulumi.Context,
	name string, args *GroupAccessArgs, opts ...pulumi.ResourceOption) (*GroupAccess, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountAccess == nil {
		return nil, errors.New("invalid value for required argument 'AccountAccess'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GroupAccess
	err := ctx.RegisterResource("temporalcloud:index/groupAccess:GroupAccess", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGroupAccess gets an existing GroupAccess resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGroupAccess(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GroupAccessState, opts ...pulumi.ResourceOption) (*GroupAccess, error) {
	var resource GroupAccess
	err := ctx.ReadResource("temporalcloud:index/groupAccess:GroupAccess", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GroupAccess resources.
type groupAccessState struct {
	// The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
	AccountAccess *string `pulumi:"accountAccess"`
	// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
	NamespaceAccesses []GroupAccessNamespaceAccess `pulumi:"namespaceAccesses"`
}

type GroupAccessState struct {
	// The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
	AccountAccess pulumi.StringPtrInput
	// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
	NamespaceAccesses GroupAccessNamespaceAccessArrayInput
}

func (GroupAccessState) ElementType() reflect.Type {
	return reflect.TypeOf((*groupAccessState)(nil)).Elem()
}

type groupAccessArgs struct {
	// The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
	AccountAccess string `pulumi:"accountAccess"`
	// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
	NamespaceAccesses []GroupAccessNamespaceAccess `pulumi:"namespaceAccesses"`
}

// The set of arguments for constructing a GroupAccess resource.
type GroupAccessArgs struct {
	// The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
	AccountAccess pulumi.StringInput
	// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
	NamespaceAccesses GroupAccessNamespaceAccessArrayInput
}

func (GroupAccessArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*groupAccessArgs)(nil)).Elem()
}

type GroupAccessInput interface {
	pulumi.Input

	ToGroupAccessOutput() GroupAccessOutput
	ToGroupAccessOutputWithContext(ctx context.Context) GroupAccessOutput
}

func (*GroupAccess) ElementType() reflect.Type {
	return reflect.TypeOf((**GroupAccess)(nil)).Elem()
}

func (i *GroupAccess) ToGroupAccessOutput() GroupAccessOutput {
	return i.ToGroupAccessOutputWithContext(context.Background())
}

func (i *GroupAccess) ToGroupAccessOutputWithContext(ctx context.Context) GroupAccessOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GroupAccessOutput)
}

// GroupAccessArrayInput is an input type that accepts GroupAccessArray and GroupAccessArrayOutput values.
// You can construct a concrete instance of `GroupAccessArrayInput` via:
//
//	GroupAccessArray{ GroupAccessArgs{...} }
type GroupAccessArrayInput interface {
	pulumi.Input

	ToGroupAccessArrayOutput() GroupAccessArrayOutput
	ToGroupAccessArrayOutputWithContext(context.Context) GroupAccessArrayOutput
}

type GroupAccessArray []GroupAccessInput

func (GroupAccessArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GroupAccess)(nil)).Elem()
}

func (i GroupAccessArray) ToGroupAccessArrayOutput() GroupAccessArrayOutput {
	return i.ToGroupAccessArrayOutputWithContext(context.Background())
}

func (i GroupAccessArray) ToGroupAccessArrayOutputWithContext(ctx context.Context) GroupAccessArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GroupAccessArrayOutput)
}

// GroupAccessMapInput is an input type that accepts GroupAccessMap and GroupAccessMapOutput values.
// You can construct a concrete instance of `GroupAccessMapInput` via:
//
//	GroupAccessMap{ "key": GroupAccessArgs{...} }
type GroupAccessMapInput interface {
	pulumi.Input

	ToGroupAccessMapOutput() GroupAccessMapOutput
	ToGroupAccessMapOutputWithContext(context.Context) GroupAccessMapOutput
}

type GroupAccessMap map[string]GroupAccessInput

func (GroupAccessMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GroupAccess)(nil)).Elem()
}

func (i GroupAccessMap) ToGroupAccessMapOutput() GroupAccessMapOutput {
	return i.ToGroupAccessMapOutputWithContext(context.Background())
}

func (i GroupAccessMap) ToGroupAccessMapOutputWithContext(ctx context.Context) GroupAccessMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GroupAccessMapOutput)
}

type GroupAccessOutput struct{ *pulumi.OutputState }

func (GroupAccessOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GroupAccess)(nil)).Elem()
}

func (o GroupAccessOutput) ToGroupAccessOutput() GroupAccessOutput {
	return o
}

func (o GroupAccessOutput) ToGroupAccessOutputWithContext(ctx context.Context) GroupAccessOutput {
	return o
}

// The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
func (o GroupAccessOutput) AccountAccess() pulumi.StringOutput {
	return o.ApplyT(func(v *GroupAccess) pulumi.StringOutput { return v.AccountAccess }).(pulumi.StringOutput)
}

// The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
func (o GroupAccessOutput) NamespaceAccesses() GroupAccessNamespaceAccessArrayOutput {
	return o.ApplyT(func(v *GroupAccess) GroupAccessNamespaceAccessArrayOutput { return v.NamespaceAccesses }).(GroupAccessNamespaceAccessArrayOutput)
}

type GroupAccessArrayOutput struct{ *pulumi.OutputState }

func (GroupAccessArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GroupAccess)(nil)).Elem()
}

func (o GroupAccessArrayOutput) ToGroupAccessArrayOutput() GroupAccessArrayOutput {
	return o
}

func (o GroupAccessArrayOutput) ToGroupAccessArrayOutputWithContext(ctx context.Context) GroupAccessArrayOutput {
	return o
}

func (o GroupAccessArrayOutput) Index(i pulumi.IntInput) GroupAccessOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GroupAccess {
		return vs[0].([]*GroupAccess)[vs[1].(int)]
	}).(GroupAccessOutput)
}

type GroupAccessMapOutput struct{ *pulumi.OutputState }

func (GroupAccessMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GroupAccess)(nil)).Elem()
}

func (o GroupAccessMapOutput) ToGroupAccessMapOutput() GroupAccessMapOutput {
	return o
}

func (o GroupAccessMapOutput) ToGroupAccessMapOutputWithContext(ctx context.Context) GroupAccessMapOutput {
	return o
}

func (o GroupAccessMapOutput) MapIndex(k pulumi.StringInput) GroupAccessOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GroupAccess {
		return vs[0].(map[string]*GroupAccess)[vs[1].(string)]
	}).(GroupAccessOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GroupAccessInput)(nil)).Elem(), &GroupAccess{})
	pulumi.RegisterInputType(reflect.TypeOf((*GroupAccessArrayInput)(nil)).Elem(), GroupAccessArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GroupAccessMapInput)(nil)).Elem(), GroupAccessMap{})
	pulumi.RegisterOutputType(GroupAccessOutput{})
	pulumi.RegisterOutputType(GroupAccessArrayOutput{})
	pulumi.RegisterOutputType(GroupAccessMapOutput{})
}
