// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package temporalcloud

import (
	"fmt"

	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "temporalcloud:index/apikey:Apikey":
		r = &Apikey{}
	case "temporalcloud:index/namespace:Namespace":
		r = &Namespace{}
	case "temporalcloud:index/namespaceSearchAttribute:NamespaceSearchAttribute":
		r = &NamespaceSearchAttribute{}
	case "temporalcloud:index/serviceAccount:ServiceAccount":
		r = &ServiceAccount{}
	case "temporalcloud:index/user:User":
		r = &User{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:temporalcloud" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"temporalcloud",
		"index/apikey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"temporalcloud",
		"index/namespace",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"temporalcloud",
		"index/namespaceSearchAttribute",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"temporalcloud",
		"index/serviceAccount",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"temporalcloud",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"temporalcloud",
		&pkg{version},
	)
}
