// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package temporalcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provisions a namespace export sink.
type NamespaceExportSink struct {
	pulumi.CustomResourceState

	// A flag indicating whether the export sink is enabled or not.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// The GCS configuration details when destinationType is GCS.
	Gcs NamespaceExportSinkGcsPtrOutput `pulumi:"gcs"`
	// The namespace under which the sink is configured. It's needed to be in the format of \n\n.\n\n
	Namespace pulumi.StringOutput `pulumi:"namespace"`
	// The S3 configuration details when destinationType is S3.
	S3 NamespaceExportSinkS3PtrOutput `pulumi:"s3"`
	// The unique name of the export sink, it can't be changed once set.
	SinkName pulumi.StringOutput                  `pulumi:"sinkName"`
	Timeouts NamespaceExportSinkTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewNamespaceExportSink registers a new resource with the given unique name, arguments, and options.
func NewNamespaceExportSink(ctx *pulumi.Context,
	name string, args *NamespaceExportSinkArgs, opts ...pulumi.ResourceOption) (*NamespaceExportSink, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Namespace == nil {
		return nil, errors.New("invalid value for required argument 'Namespace'")
	}
	if args.SinkName == nil {
		return nil, errors.New("invalid value for required argument 'SinkName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NamespaceExportSink
	err := ctx.RegisterResource("temporalcloud:index/namespaceExportSink:NamespaceExportSink", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNamespaceExportSink gets an existing NamespaceExportSink resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNamespaceExportSink(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NamespaceExportSinkState, opts ...pulumi.ResourceOption) (*NamespaceExportSink, error) {
	var resource NamespaceExportSink
	err := ctx.ReadResource("temporalcloud:index/namespaceExportSink:NamespaceExportSink", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NamespaceExportSink resources.
type namespaceExportSinkState struct {
	// A flag indicating whether the export sink is enabled or not.
	Enabled *bool `pulumi:"enabled"`
	// The GCS configuration details when destinationType is GCS.
	Gcs *NamespaceExportSinkGcs `pulumi:"gcs"`
	// The namespace under which the sink is configured. It's needed to be in the format of \n\n.\n\n
	Namespace *string `pulumi:"namespace"`
	// The S3 configuration details when destinationType is S3.
	S3 *NamespaceExportSinkS3 `pulumi:"s3"`
	// The unique name of the export sink, it can't be changed once set.
	SinkName *string                      `pulumi:"sinkName"`
	Timeouts *NamespaceExportSinkTimeouts `pulumi:"timeouts"`
}

type NamespaceExportSinkState struct {
	// A flag indicating whether the export sink is enabled or not.
	Enabled pulumi.BoolPtrInput
	// The GCS configuration details when destinationType is GCS.
	Gcs NamespaceExportSinkGcsPtrInput
	// The namespace under which the sink is configured. It's needed to be in the format of \n\n.\n\n
	Namespace pulumi.StringPtrInput
	// The S3 configuration details when destinationType is S3.
	S3 NamespaceExportSinkS3PtrInput
	// The unique name of the export sink, it can't be changed once set.
	SinkName pulumi.StringPtrInput
	Timeouts NamespaceExportSinkTimeoutsPtrInput
}

func (NamespaceExportSinkState) ElementType() reflect.Type {
	return reflect.TypeOf((*namespaceExportSinkState)(nil)).Elem()
}

type namespaceExportSinkArgs struct {
	// A flag indicating whether the export sink is enabled or not.
	Enabled *bool `pulumi:"enabled"`
	// The GCS configuration details when destinationType is GCS.
	Gcs *NamespaceExportSinkGcs `pulumi:"gcs"`
	// The namespace under which the sink is configured. It's needed to be in the format of \n\n.\n\n
	Namespace string `pulumi:"namespace"`
	// The S3 configuration details when destinationType is S3.
	S3 *NamespaceExportSinkS3 `pulumi:"s3"`
	// The unique name of the export sink, it can't be changed once set.
	SinkName string                       `pulumi:"sinkName"`
	Timeouts *NamespaceExportSinkTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a NamespaceExportSink resource.
type NamespaceExportSinkArgs struct {
	// A flag indicating whether the export sink is enabled or not.
	Enabled pulumi.BoolPtrInput
	// The GCS configuration details when destinationType is GCS.
	Gcs NamespaceExportSinkGcsPtrInput
	// The namespace under which the sink is configured. It's needed to be in the format of \n\n.\n\n
	Namespace pulumi.StringInput
	// The S3 configuration details when destinationType is S3.
	S3 NamespaceExportSinkS3PtrInput
	// The unique name of the export sink, it can't be changed once set.
	SinkName pulumi.StringInput
	Timeouts NamespaceExportSinkTimeoutsPtrInput
}

func (NamespaceExportSinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*namespaceExportSinkArgs)(nil)).Elem()
}

type NamespaceExportSinkInput interface {
	pulumi.Input

	ToNamespaceExportSinkOutput() NamespaceExportSinkOutput
	ToNamespaceExportSinkOutputWithContext(ctx context.Context) NamespaceExportSinkOutput
}

func (*NamespaceExportSink) ElementType() reflect.Type {
	return reflect.TypeOf((**NamespaceExportSink)(nil)).Elem()
}

func (i *NamespaceExportSink) ToNamespaceExportSinkOutput() NamespaceExportSinkOutput {
	return i.ToNamespaceExportSinkOutputWithContext(context.Background())
}

func (i *NamespaceExportSink) ToNamespaceExportSinkOutputWithContext(ctx context.Context) NamespaceExportSinkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NamespaceExportSinkOutput)
}

// NamespaceExportSinkArrayInput is an input type that accepts NamespaceExportSinkArray and NamespaceExportSinkArrayOutput values.
// You can construct a concrete instance of `NamespaceExportSinkArrayInput` via:
//
//	NamespaceExportSinkArray{ NamespaceExportSinkArgs{...} }
type NamespaceExportSinkArrayInput interface {
	pulumi.Input

	ToNamespaceExportSinkArrayOutput() NamespaceExportSinkArrayOutput
	ToNamespaceExportSinkArrayOutputWithContext(context.Context) NamespaceExportSinkArrayOutput
}

type NamespaceExportSinkArray []NamespaceExportSinkInput

func (NamespaceExportSinkArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NamespaceExportSink)(nil)).Elem()
}

func (i NamespaceExportSinkArray) ToNamespaceExportSinkArrayOutput() NamespaceExportSinkArrayOutput {
	return i.ToNamespaceExportSinkArrayOutputWithContext(context.Background())
}

func (i NamespaceExportSinkArray) ToNamespaceExportSinkArrayOutputWithContext(ctx context.Context) NamespaceExportSinkArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NamespaceExportSinkArrayOutput)
}

// NamespaceExportSinkMapInput is an input type that accepts NamespaceExportSinkMap and NamespaceExportSinkMapOutput values.
// You can construct a concrete instance of `NamespaceExportSinkMapInput` via:
//
//	NamespaceExportSinkMap{ "key": NamespaceExportSinkArgs{...} }
type NamespaceExportSinkMapInput interface {
	pulumi.Input

	ToNamespaceExportSinkMapOutput() NamespaceExportSinkMapOutput
	ToNamespaceExportSinkMapOutputWithContext(context.Context) NamespaceExportSinkMapOutput
}

type NamespaceExportSinkMap map[string]NamespaceExportSinkInput

func (NamespaceExportSinkMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NamespaceExportSink)(nil)).Elem()
}

func (i NamespaceExportSinkMap) ToNamespaceExportSinkMapOutput() NamespaceExportSinkMapOutput {
	return i.ToNamespaceExportSinkMapOutputWithContext(context.Background())
}

func (i NamespaceExportSinkMap) ToNamespaceExportSinkMapOutputWithContext(ctx context.Context) NamespaceExportSinkMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NamespaceExportSinkMapOutput)
}

type NamespaceExportSinkOutput struct{ *pulumi.OutputState }

func (NamespaceExportSinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NamespaceExportSink)(nil)).Elem()
}

func (o NamespaceExportSinkOutput) ToNamespaceExportSinkOutput() NamespaceExportSinkOutput {
	return o
}

func (o NamespaceExportSinkOutput) ToNamespaceExportSinkOutputWithContext(ctx context.Context) NamespaceExportSinkOutput {
	return o
}

// A flag indicating whether the export sink is enabled or not.
func (o NamespaceExportSinkOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *NamespaceExportSink) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// The GCS configuration details when destinationType is GCS.
func (o NamespaceExportSinkOutput) Gcs() NamespaceExportSinkGcsPtrOutput {
	return o.ApplyT(func(v *NamespaceExportSink) NamespaceExportSinkGcsPtrOutput { return v.Gcs }).(NamespaceExportSinkGcsPtrOutput)
}

// The namespace under which the sink is configured. It's needed to be in the format of \n\n.\n\n
func (o NamespaceExportSinkOutput) Namespace() pulumi.StringOutput {
	return o.ApplyT(func(v *NamespaceExportSink) pulumi.StringOutput { return v.Namespace }).(pulumi.StringOutput)
}

// The S3 configuration details when destinationType is S3.
func (o NamespaceExportSinkOutput) S3() NamespaceExportSinkS3PtrOutput {
	return o.ApplyT(func(v *NamespaceExportSink) NamespaceExportSinkS3PtrOutput { return v.S3 }).(NamespaceExportSinkS3PtrOutput)
}

// The unique name of the export sink, it can't be changed once set.
func (o NamespaceExportSinkOutput) SinkName() pulumi.StringOutput {
	return o.ApplyT(func(v *NamespaceExportSink) pulumi.StringOutput { return v.SinkName }).(pulumi.StringOutput)
}

func (o NamespaceExportSinkOutput) Timeouts() NamespaceExportSinkTimeoutsPtrOutput {
	return o.ApplyT(func(v *NamespaceExportSink) NamespaceExportSinkTimeoutsPtrOutput { return v.Timeouts }).(NamespaceExportSinkTimeoutsPtrOutput)
}

type NamespaceExportSinkArrayOutput struct{ *pulumi.OutputState }

func (NamespaceExportSinkArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NamespaceExportSink)(nil)).Elem()
}

func (o NamespaceExportSinkArrayOutput) ToNamespaceExportSinkArrayOutput() NamespaceExportSinkArrayOutput {
	return o
}

func (o NamespaceExportSinkArrayOutput) ToNamespaceExportSinkArrayOutputWithContext(ctx context.Context) NamespaceExportSinkArrayOutput {
	return o
}

func (o NamespaceExportSinkArrayOutput) Index(i pulumi.IntInput) NamespaceExportSinkOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NamespaceExportSink {
		return vs[0].([]*NamespaceExportSink)[vs[1].(int)]
	}).(NamespaceExportSinkOutput)
}

type NamespaceExportSinkMapOutput struct{ *pulumi.OutputState }

func (NamespaceExportSinkMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NamespaceExportSink)(nil)).Elem()
}

func (o NamespaceExportSinkMapOutput) ToNamespaceExportSinkMapOutput() NamespaceExportSinkMapOutput {
	return o
}

func (o NamespaceExportSinkMapOutput) ToNamespaceExportSinkMapOutputWithContext(ctx context.Context) NamespaceExportSinkMapOutput {
	return o
}

func (o NamespaceExportSinkMapOutput) MapIndex(k pulumi.StringInput) NamespaceExportSinkOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NamespaceExportSink {
		return vs[0].(map[string]*NamespaceExportSink)[vs[1].(string)]
	}).(NamespaceExportSinkOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NamespaceExportSinkInput)(nil)).Elem(), &NamespaceExportSink{})
	pulumi.RegisterInputType(reflect.TypeOf((*NamespaceExportSinkArrayInput)(nil)).Elem(), NamespaceExportSinkArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NamespaceExportSinkMapInput)(nil)).Elem(), NamespaceExportSinkMap{})
	pulumi.RegisterOutputType(NamespaceExportSinkOutput{})
	pulumi.RegisterOutputType(NamespaceExportSinkArrayOutput{})
	pulumi.RegisterOutputType(NamespaceExportSinkMapOutput{})
}
