// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package temporalcloud

import (
	"context"
	"reflect"

	"github.com/Grip-Security/pulumi-temporalcloud/sdk/go/temporalcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the temporalcloud package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// The ID of the account to operate on. Prevents accidental mutation of accounts other than that provided.
	AllowedAccountId pulumi.StringPtrOutput `pulumi:"allowedAccountId"`
	// The API key for Temporal Cloud. See [this documentation](https://docs.temporal.io/cloud/api-keys) for information on how
	// to obtain an API key.
	ApiKey pulumi.StringPtrOutput `pulumi:"apiKey"`
	// The endpoint for the Temporal Cloud API. Defaults to `saas-api.tmprl.cloud:443`.
	Endpoint pulumi.StringPtrOutput `pulumi:"endpoint"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ApiKey != nil {
		args.ApiKey = pulumi.ToSecret(args.ApiKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:temporalcloud", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// If set to True, it allows for an insecure connection to the Temporal Cloud API. This should never be set to 'true' in
	// production and defaults to false.
	AllowInsecure *bool `pulumi:"allowInsecure"`
	// The ID of the account to operate on. Prevents accidental mutation of accounts other than that provided.
	AllowedAccountId *string `pulumi:"allowedAccountId"`
	// The API key for Temporal Cloud. See [this documentation](https://docs.temporal.io/cloud/api-keys) for information on how
	// to obtain an API key.
	ApiKey *string `pulumi:"apiKey"`
	// The endpoint for the Temporal Cloud API. Defaults to `saas-api.tmprl.cloud:443`.
	Endpoint *string `pulumi:"endpoint"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// If set to True, it allows for an insecure connection to the Temporal Cloud API. This should never be set to 'true' in
	// production and defaults to false.
	AllowInsecure pulumi.BoolPtrInput
	// The ID of the account to operate on. Prevents accidental mutation of accounts other than that provided.
	AllowedAccountId pulumi.StringPtrInput
	// The API key for Temporal Cloud. See [this documentation](https://docs.temporal.io/cloud/api-keys) for information on how
	// to obtain an API key.
	ApiKey pulumi.StringPtrInput
	// The endpoint for the Temporal Cloud API. Defaults to `saas-api.tmprl.cloud:443`.
	Endpoint pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The ID of the account to operate on. Prevents accidental mutation of accounts other than that provided.
func (o ProviderOutput) AllowedAccountId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.AllowedAccountId }).(pulumi.StringPtrOutput)
}

// The API key for Temporal Cloud. See [this documentation](https://docs.temporal.io/cloud/api-keys) for information on how
// to obtain an API key.
func (o ProviderOutput) ApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiKey }).(pulumi.StringPtrOutput)
}

// The endpoint for the Temporal Cloud API. Defaults to `saas-api.tmprl.cloud:443`.
func (o ProviderOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Endpoint }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
