# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetUserResult',
    'AwaitableGetUserResult',
    'get_user',
    'get_user_output',
]

@pulumi.output_type
class GetUserResult:
    """
    A collection of values returned by getUser.
    """
    def __init__(__self__, account_access=None, created_at=None, email=None, id=None, namespace_accesses=None, state=None, updated_at=None):
        if account_access and not isinstance(account_access, str):
            raise TypeError("Expected argument 'account_access' to be a str")
        pulumi.set(__self__, "account_access", account_access)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if email and not isinstance(email, str):
            raise TypeError("Expected argument 'email' to be a str")
        pulumi.set(__self__, "email", email)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if namespace_accesses and not isinstance(namespace_accesses, list):
            raise TypeError("Expected argument 'namespace_accesses' to be a list")
        pulumi.set(__self__, "namespace_accesses", namespace_accesses)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)

    @property
    @pulumi.getter(name="accountAccess")
    def account_access(self) -> builtins.str:
        """
        The role on the account. Must be one of admin, developer, or read (case-insensitive).
        """
        return pulumi.get(self, "account_access")

    @property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> builtins.str:
        """
        The creation time of the User.
        """
        return pulumi.get(self, "created_at")

    @property
    @pulumi.getter
    def email(self) -> builtins.str:
        """
        The email of the User.
        """
        return pulumi.get(self, "email")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        """
        The unique identifier of the User.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="namespaceAccesses")
    def namespace_accesses(self) -> Sequence['outputs.GetUserNamespaceAccessResult']:
        """
        The set of namespace permissions for this user, including each namespace and its role.
        """
        return pulumi.get(self, "namespace_accesses")

    @property
    @pulumi.getter
    def state(self) -> builtins.str:
        """
        The current state of the User.
        """
        return pulumi.get(self, "state")

    @property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> builtins.str:
        """
        The last update time of the User.
        """
        return pulumi.get(self, "updated_at")


class AwaitableGetUserResult(GetUserResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetUserResult(
            account_access=self.account_access,
            created_at=self.created_at,
            email=self.email,
            id=self.id,
            namespace_accesses=self.namespace_accesses,
            state=self.state,
            updated_at=self.updated_at)


def get_user(id: Optional[builtins.str] = None,
             namespace_accesses: Optional[Sequence[Union['GetUserNamespaceAccessArgs', 'GetUserNamespaceAccessArgsDict']]] = None,
             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetUserResult:
    """
    Fetches details about a User.


    :param builtins.str id: The unique identifier of the User.
    :param Sequence[Union['GetUserNamespaceAccessArgs', 'GetUserNamespaceAccessArgsDict']] namespace_accesses: The set of namespace permissions for this user, including each namespace and its role.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['namespaceAccesses'] = namespace_accesses
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('temporalcloud:index/getUser:getUser', __args__, opts=opts, typ=GetUserResult).value

    return AwaitableGetUserResult(
        account_access=pulumi.get(__ret__, 'account_access'),
        created_at=pulumi.get(__ret__, 'created_at'),
        email=pulumi.get(__ret__, 'email'),
        id=pulumi.get(__ret__, 'id'),
        namespace_accesses=pulumi.get(__ret__, 'namespace_accesses'),
        state=pulumi.get(__ret__, 'state'),
        updated_at=pulumi.get(__ret__, 'updated_at'))
def get_user_output(id: Optional[pulumi.Input[builtins.str]] = None,
                    namespace_accesses: Optional[pulumi.Input[Optional[Sequence[Union['GetUserNamespaceAccessArgs', 'GetUserNamespaceAccessArgsDict']]]]] = None,
                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetUserResult]:
    """
    Fetches details about a User.


    :param builtins.str id: The unique identifier of the User.
    :param Sequence[Union['GetUserNamespaceAccessArgs', 'GetUserNamespaceAccessArgsDict']] namespace_accesses: The set of namespace permissions for this user, including each namespace and its role.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['namespaceAccesses'] = namespace_accesses
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('temporalcloud:index/getUser:getUser', __args__, opts=opts, typ=GetUserResult)
    return __ret__.apply(lambda __response__: GetUserResult(
        account_access=pulumi.get(__response__, 'account_access'),
        created_at=pulumi.get(__response__, 'created_at'),
        email=pulumi.get(__response__, 'email'),
        id=pulumi.get(__response__, 'id'),
        namespace_accesses=pulumi.get(__response__, 'namespace_accesses'),
        state=pulumi.get(__response__, 'state'),
        updated_at=pulumi.get(__response__, 'updated_at')))
