# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetNexusEndpointsResult',
    'AwaitableGetNexusEndpointsResult',
    'get_nexus_endpoints',
    'get_nexus_endpoints_output',
]

@pulumi.output_type
class GetNexusEndpointsResult:
    """
    A collection of values returned by getNexusEndpoints.
    """
    def __init__(__self__, id=None, nexus_endpoints=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if nexus_endpoints and not isinstance(nexus_endpoints, list):
            raise TypeError("Expected argument 'nexus_endpoints' to be a list")
        pulumi.set(__self__, "nexus_endpoints", nexus_endpoints)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the Nexus Endpoints data source.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="nexusEndpoints")
    def nexus_endpoints(self) -> Sequence['outputs.GetNexusEndpointsNexusEndpointResult']:
        """
        The list of Nexus Endpoints.
        """
        return pulumi.get(self, "nexus_endpoints")


class AwaitableGetNexusEndpointsResult(GetNexusEndpointsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNexusEndpointsResult(
            id=self.id,
            nexus_endpoints=self.nexus_endpoints)


def get_nexus_endpoints(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNexusEndpointsResult:
    """
    Fetches details about all Nexus Endpoints.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_temporalcloud as temporalcloud

    my_nexus_endpoints = temporalcloud.get_nexus_endpoints()
    pulumi.export("nexusEndpoints", my_nexus_endpoints.nexus_endpoints)
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('temporalcloud:index/getNexusEndpoints:getNexusEndpoints', __args__, opts=opts, typ=GetNexusEndpointsResult).value

    return AwaitableGetNexusEndpointsResult(
        id=pulumi.get(__ret__, 'id'),
        nexus_endpoints=pulumi.get(__ret__, 'nexus_endpoints'))
def get_nexus_endpoints_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetNexusEndpointsResult]:
    """
    Fetches details about all Nexus Endpoints.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_temporalcloud as temporalcloud

    my_nexus_endpoints = temporalcloud.get_nexus_endpoints()
    pulumi.export("nexusEndpoints", my_nexus_endpoints.nexus_endpoints)
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('temporalcloud:index/getNexusEndpoints:getNexusEndpoints', __args__, opts=opts, typ=GetNexusEndpointsResult)
    return __ret__.apply(lambda __response__: GetNexusEndpointsResult(
        id=pulumi.get(__response__, 'id'),
        nexus_endpoints=pulumi.get(__response__, 'nexus_endpoints')))
