# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetConnectivityRuleResult',
    'AwaitableGetConnectivityRuleResult',
    'get_connectivity_rule',
    'get_connectivity_rule_output',
]

@pulumi.output_type
class GetConnectivityRuleResult:
    """
    A collection of values returned by getConnectivityRule.
    """
    def __init__(__self__, connection_id=None, connectivity_type=None, created_at=None, gcp_project_id=None, id=None, region=None, state=None):
        if connection_id and not isinstance(connection_id, str):
            raise TypeError("Expected argument 'connection_id' to be a str")
        pulumi.set(__self__, "connection_id", connection_id)
        if connectivity_type and not isinstance(connectivity_type, str):
            raise TypeError("Expected argument 'connectivity_type' to be a str")
        pulumi.set(__self__, "connectivity_type", connectivity_type)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if gcp_project_id and not isinstance(gcp_project_id, str):
            raise TypeError("Expected argument 'gcp_project_id' to be a str")
        pulumi.set(__self__, "gcp_project_id", gcp_project_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)

    @_builtins.property
    @pulumi.getter(name="connectionId")
    def connection_id(self) -> _builtins.str:
        """
        The ID of the connection to the connectivity rule.
        """
        return pulumi.get(self, "connection_id")

    @_builtins.property
    @pulumi.getter(name="connectivityType")
    def connectivity_type(self) -> _builtins.str:
        """
        The type of connectivity.
        """
        return pulumi.get(self, "connectivity_type")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        The time the connectivity rule was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="gcpProjectId")
    def gcp_project_id(self) -> _builtins.str:
        """
        The GCP project ID of the connectivity rule.
        """
        return pulumi.get(self, "gcp_project_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the connectivity rule across all Temporal Cloud tenants.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        """
        The region of the connectivity rule.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def state(self) -> _builtins.str:
        """
        The current state of the connectivity rule.
        """
        return pulumi.get(self, "state")


class AwaitableGetConnectivityRuleResult(GetConnectivityRuleResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetConnectivityRuleResult(
            connection_id=self.connection_id,
            connectivity_type=self.connectivity_type,
            created_at=self.created_at,
            gcp_project_id=self.gcp_project_id,
            id=self.id,
            region=self.region,
            state=self.state)


def get_connectivity_rule(id: Optional[_builtins.str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetConnectivityRuleResult:
    """
    Fetches details about a connectivity rule.


    :param _builtins.str id: The unique identifier of the connectivity rule across all Temporal Cloud tenants.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('temporalcloud:index/getConnectivityRule:getConnectivityRule', __args__, opts=opts, typ=GetConnectivityRuleResult).value

    return AwaitableGetConnectivityRuleResult(
        connection_id=pulumi.get(__ret__, 'connection_id'),
        connectivity_type=pulumi.get(__ret__, 'connectivity_type'),
        created_at=pulumi.get(__ret__, 'created_at'),
        gcp_project_id=pulumi.get(__ret__, 'gcp_project_id'),
        id=pulumi.get(__ret__, 'id'),
        region=pulumi.get(__ret__, 'region'),
        state=pulumi.get(__ret__, 'state'))
def get_connectivity_rule_output(id: Optional[pulumi.Input[_builtins.str]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetConnectivityRuleResult]:
    """
    Fetches details about a connectivity rule.


    :param _builtins.str id: The unique identifier of the connectivity rule across all Temporal Cloud tenants.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('temporalcloud:index/getConnectivityRule:getConnectivityRule', __args__, opts=opts, typ=GetConnectivityRuleResult)
    return __ret__.apply(lambda __response__: GetConnectivityRuleResult(
        connection_id=pulumi.get(__response__, 'connection_id'),
        connectivity_type=pulumi.get(__response__, 'connectivity_type'),
        created_at=pulumi.get(__response__, 'created_at'),
        gcp_project_id=pulumi.get(__response__, 'gcp_project_id'),
        id=pulumi.get(__response__, 'id'),
        region=pulumi.get(__response__, 'region'),
        state=pulumi.get(__response__, 'state')))
