# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetNexusEndpointResult',
    'AwaitableGetNexusEndpointResult',
    'get_nexus_endpoint',
    'get_nexus_endpoint_output',
]

@pulumi.output_type
class GetNexusEndpointResult:
    """
    A collection of values returned by getNexusEndpoint.
    """
    def __init__(__self__, allowed_caller_namespaces=None, created_at=None, description=None, id=None, name=None, state=None, updated_at=None, worker_target=None):
        if allowed_caller_namespaces and not isinstance(allowed_caller_namespaces, list):
            raise TypeError("Expected argument 'allowed_caller_namespaces' to be a list")
        pulumi.set(__self__, "allowed_caller_namespaces", allowed_caller_namespaces)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)
        if worker_target and not isinstance(worker_target, dict):
            raise TypeError("Expected argument 'worker_target' to be a dict")
        pulumi.set(__self__, "worker_target", worker_target)

    @_builtins.property
    @pulumi.getter(name="allowedCallerNamespaces")
    def allowed_caller_namespaces(self) -> Sequence[_builtins.str]:
        """
        Namespace Id(s) that are allowed to call this Endpoint.
        """
        return pulumi.get(self, "allowed_caller_namespaces")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        The creation time of the Nexus Endpoint.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        The description of the Nexus Endpoint.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the Nexus Endpoint.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the endpoint. Unique within an account and match `^[a-zA-Z][a-zA-Z0-9\\-]*[a-zA-Z0-9]$`
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def state(self) -> _builtins.str:
        """
        The current state of the Nexus Endpoint.
        """
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        """
        The last update time of the Nexus Endpoint.
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="workerTarget")
    def worker_target(self) -> 'outputs.GetNexusEndpointWorkerTargetResult':
        """
        The target spec for routing nexus requests to a specific cloud namespace worker.
        """
        return pulumi.get(self, "worker_target")


class AwaitableGetNexusEndpointResult(GetNexusEndpointResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNexusEndpointResult(
            allowed_caller_namespaces=self.allowed_caller_namespaces,
            created_at=self.created_at,
            description=self.description,
            id=self.id,
            name=self.name,
            state=self.state,
            updated_at=self.updated_at,
            worker_target=self.worker_target)


def get_nexus_endpoint(description: Optional[_builtins.str] = None,
                       id: Optional[_builtins.str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNexusEndpointResult:
    """
    Fetches details about a Nexus Endpoint.


    :param _builtins.str description: The description of the Nexus Endpoint.
    :param _builtins.str id: The unique identifier of the Nexus Endpoint.
    """
    __args__ = dict()
    __args__['description'] = description
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('temporalcloud:index/getNexusEndpoint:getNexusEndpoint', __args__, opts=opts, typ=GetNexusEndpointResult).value

    return AwaitableGetNexusEndpointResult(
        allowed_caller_namespaces=pulumi.get(__ret__, 'allowed_caller_namespaces'),
        created_at=pulumi.get(__ret__, 'created_at'),
        description=pulumi.get(__ret__, 'description'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        state=pulumi.get(__ret__, 'state'),
        updated_at=pulumi.get(__ret__, 'updated_at'),
        worker_target=pulumi.get(__ret__, 'worker_target'))
def get_nexus_endpoint_output(description: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                              id: Optional[pulumi.Input[_builtins.str]] = None,
                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetNexusEndpointResult]:
    """
    Fetches details about a Nexus Endpoint.


    :param _builtins.str description: The description of the Nexus Endpoint.
    :param _builtins.str id: The unique identifier of the Nexus Endpoint.
    """
    __args__ = dict()
    __args__['description'] = description
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('temporalcloud:index/getNexusEndpoint:getNexusEndpoint', __args__, opts=opts, typ=GetNexusEndpointResult)
    return __ret__.apply(lambda __response__: GetNexusEndpointResult(
        allowed_caller_namespaces=pulumi.get(__response__, 'allowed_caller_namespaces'),
        created_at=pulumi.get(__response__, 'created_at'),
        description=pulumi.get(__response__, 'description'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        state=pulumi.get(__response__, 'state'),
        updated_at=pulumi.get(__response__, 'updated_at'),
        worker_target=pulumi.get(__response__, 'worker_target')))
