# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['GroupAccessArgs', 'GroupAccess']

@pulumi.input_type
class GroupAccessArgs:
    def __init__(__self__, *,
                 account_access: pulumi.Input[builtins.str],
                 namespace_accesses: Optional[pulumi.Input[Sequence[pulumi.Input['GroupAccessNamespaceAccessArgs']]]] = None):
        """
        The set of arguments for constructing a GroupAccess resource.
        :param pulumi.Input[builtins.str] account_access: The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
        :param pulumi.Input[Sequence[pulumi.Input['GroupAccessNamespaceAccessArgs']]] namespace_accesses: The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
        """
        pulumi.set(__self__, "account_access", account_access)
        if namespace_accesses is not None:
            pulumi.set(__self__, "namespace_accesses", namespace_accesses)

    @property
    @pulumi.getter(name="accountAccess")
    def account_access(self) -> pulumi.Input[builtins.str]:
        """
        The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
        """
        return pulumi.get(self, "account_access")

    @account_access.setter
    def account_access(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "account_access", value)

    @property
    @pulumi.getter(name="namespaceAccesses")
    def namespace_accesses(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['GroupAccessNamespaceAccessArgs']]]]:
        """
        The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
        """
        return pulumi.get(self, "namespace_accesses")

    @namespace_accesses.setter
    def namespace_accesses(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['GroupAccessNamespaceAccessArgs']]]]):
        pulumi.set(self, "namespace_accesses", value)


@pulumi.input_type
class _GroupAccessState:
    def __init__(__self__, *,
                 account_access: Optional[pulumi.Input[builtins.str]] = None,
                 namespace_accesses: Optional[pulumi.Input[Sequence[pulumi.Input['GroupAccessNamespaceAccessArgs']]]] = None):
        """
        Input properties used for looking up and filtering GroupAccess resources.
        :param pulumi.Input[builtins.str] account_access: The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
        :param pulumi.Input[Sequence[pulumi.Input['GroupAccessNamespaceAccessArgs']]] namespace_accesses: The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
        """
        if account_access is not None:
            pulumi.set(__self__, "account_access", account_access)
        if namespace_accesses is not None:
            pulumi.set(__self__, "namespace_accesses", namespace_accesses)

    @property
    @pulumi.getter(name="accountAccess")
    def account_access(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
        """
        return pulumi.get(self, "account_access")

    @account_access.setter
    def account_access(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "account_access", value)

    @property
    @pulumi.getter(name="namespaceAccesses")
    def namespace_accesses(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['GroupAccessNamespaceAccessArgs']]]]:
        """
        The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
        """
        return pulumi.get(self, "namespace_accesses")

    @namespace_accesses.setter
    def namespace_accesses(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['GroupAccessNamespaceAccessArgs']]]]):
        pulumi.set(self, "namespace_accesses", value)


@pulumi.type_token("temporalcloud:index/groupAccess:GroupAccess")
class GroupAccess(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_access: Optional[pulumi.Input[builtins.str]] = None,
                 namespace_accesses: Optional[pulumi.Input[Sequence[pulumi.Input[Union['GroupAccessNamespaceAccessArgs', 'GroupAccessNamespaceAccessArgsDict']]]]] = None,
                 __props__=None):
        """
        Provisions Temporal Cloud group access.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] account_access: The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
        :param pulumi.Input[Sequence[pulumi.Input[Union['GroupAccessNamespaceAccessArgs', 'GroupAccessNamespaceAccessArgsDict']]]] namespace_accesses: The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: GroupAccessArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Provisions Temporal Cloud group access.

        :param str resource_name: The name of the resource.
        :param GroupAccessArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(GroupAccessArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_access: Optional[pulumi.Input[builtins.str]] = None,
                 namespace_accesses: Optional[pulumi.Input[Sequence[pulumi.Input[Union['GroupAccessNamespaceAccessArgs', 'GroupAccessNamespaceAccessArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = GroupAccessArgs.__new__(GroupAccessArgs)

            if account_access is None and not opts.urn:
                raise TypeError("Missing required property 'account_access'")
            __props__.__dict__["account_access"] = account_access
            __props__.__dict__["namespace_accesses"] = namespace_accesses
        super(GroupAccess, __self__).__init__(
            'temporalcloud:index/groupAccess:GroupAccess',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            account_access: Optional[pulumi.Input[builtins.str]] = None,
            namespace_accesses: Optional[pulumi.Input[Sequence[pulumi.Input[Union['GroupAccessNamespaceAccessArgs', 'GroupAccessNamespaceAccessArgsDict']]]]] = None) -> 'GroupAccess':
        """
        Get an existing GroupAccess resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] account_access: The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
        :param pulumi.Input[Sequence[pulumi.Input[Union['GroupAccessNamespaceAccessArgs', 'GroupAccessNamespaceAccessArgsDict']]]] namespace_accesses: The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _GroupAccessState.__new__(_GroupAccessState)

        __props__.__dict__["account_access"] = account_access
        __props__.__dict__["namespace_accesses"] = namespace_accesses
        return GroupAccess(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="accountAccess")
    def account_access(self) -> pulumi.Output[builtins.str]:
        """
        The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
        """
        return pulumi.get(self, "account_access")

    @property
    @pulumi.getter(name="namespaceAccesses")
    def namespace_accesses(self) -> pulumi.Output[Optional[Sequence['outputs.GroupAccessNamespaceAccess']]]:
        """
        The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
        """
        return pulumi.get(self, "namespace_accesses")

