// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Inputs
{

    public sealed class GetNamespaceCertificateFilterInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The certificate's common name.
        /// </summary>
        [Input("commonName", required: true)]
        public Input<string> CommonName { get; set; } = null!;

        /// <summary>
        /// The certificate's organization.
        /// </summary>
        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        /// <summary>
        /// The certificate's organizational unit.
        /// </summary>
        [Input("organizationalUnit", required: true)]
        public Input<string> OrganizationalUnit { get; set; } = null!;

        /// <summary>
        /// The certificate's subject alternative name (or SAN).
        /// </summary>
        [Input("subjectAlternativeName", required: true)]
        public Input<string> SubjectAlternativeName { get; set; } = null!;

        public GetNamespaceCertificateFilterInputArgs()
        {
        }
        public static new GetNamespaceCertificateFilterInputArgs Empty => new GetNamespaceCertificateFilterInputArgs();
    }
}
