// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Inputs
{

    public sealed class GetNamespacePrivateConnectivityAwsPrivateLinkInfoArgs : global::Pulumi.InvokeArgs
    {
        [Input("allowedPrincipalArns", required: true)]
        private List<string>? _allowedPrincipalArns;

        /// <summary>
        /// The list of principal arns that are allowed to access the namespace on the private link.
        /// </summary>
        public List<string> AllowedPrincipalArns
        {
            get => _allowedPrincipalArns ?? (_allowedPrincipalArns = new List<string>());
            set => _allowedPrincipalArns = value;
        }

        [Input("vpcEndpointServiceNames", required: true)]
        private List<string>? _vpcEndpointServiceNames;

        /// <summary>
        /// The list of vpc endpoint service names that are associated with the namespace.
        /// </summary>
        public List<string> VpcEndpointServiceNames
        {
            get => _vpcEndpointServiceNames ?? (_vpcEndpointServiceNames = new List<string>());
            set => _vpcEndpointServiceNames = value;
        }

        public GetNamespacePrivateConnectivityAwsPrivateLinkInfoArgs()
        {
        }
        public static new GetNamespacePrivateConnectivityAwsPrivateLinkInfoArgs Empty => new GetNamespacePrivateConnectivityAwsPrivateLinkInfoArgs();
    }
}
