// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Inputs
{

    public sealed class GetNamespacePrivateConnectivityAwsPrivateLinkInfoInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowedPrincipalArns", required: true)]
        private InputList<string>? _allowedPrincipalArns;

        /// <summary>
        /// The list of principal arns that are allowed to access the namespace on the private link.
        /// </summary>
        public InputList<string> AllowedPrincipalArns
        {
            get => _allowedPrincipalArns ?? (_allowedPrincipalArns = new InputList<string>());
            set => _allowedPrincipalArns = value;
        }

        [Input("vpcEndpointServiceNames", required: true)]
        private InputList<string>? _vpcEndpointServiceNames;

        /// <summary>
        /// The list of vpc endpoint service names that are associated with the namespace.
        /// </summary>
        public InputList<string> VpcEndpointServiceNames
        {
            get => _vpcEndpointServiceNames ?? (_vpcEndpointServiceNames = new InputList<string>());
            set => _vpcEndpointServiceNames = value;
        }

        public GetNamespacePrivateConnectivityAwsPrivateLinkInfoInputArgs()
        {
        }
        public static new GetNamespacePrivateConnectivityAwsPrivateLinkInfoInputArgs Empty => new GetNamespacePrivateConnectivityAwsPrivateLinkInfoInputArgs();
    }
}
