// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Inputs
{

    public sealed class GetNamespaceCodecServerInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The endpoint of the codec server.
        /// </summary>
        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        /// <summary>
        /// If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
        /// </summary>
        [Input("includeCrossOriginCredentials", required: true)]
        public Input<bool> IncludeCrossOriginCredentials { get; set; } = null!;

        /// <summary>
        /// If true, Temporal Cloud will pass the access token to the codec server upon each request.
        /// </summary>
        [Input("passAccessToken", required: true)]
        public Input<bool> PassAccessToken { get; set; } = null!;

        public GetNamespaceCodecServerInputArgs()
        {
        }
        public static new GetNamespaceCodecServerInputArgs Empty => new GetNamespaceCodecServerInputArgs();
    }
}
