// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Inputs
{

    public sealed class GetNamespaceCertificateFilterArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The certificate's common name.
        /// </summary>
        [Input("commonName", required: true)]
        public string CommonName { get; set; } = null!;

        /// <summary>
        /// The certificate's organization.
        /// </summary>
        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        /// <summary>
        /// The certificate's organizational unit.
        /// </summary>
        [Input("organizationalUnit", required: true)]
        public string OrganizationalUnit { get; set; } = null!;

        /// <summary>
        /// The certificate's subject alternative name (or SAN).
        /// </summary>
        [Input("subjectAlternativeName", required: true)]
        public string SubjectAlternativeName { get; set; } = null!;

        public GetNamespaceCertificateFilterArgs()
        {
        }
        public static new GetNamespaceCertificateFilterArgs Empty => new GetNamespaceCertificateFilterArgs();
    }
}
