// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Inputs
{

    public sealed class GetServiceAccountNamespaceAccessArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The namespace to assign permissions to.
        /// </summary>
        [Input("namespaceId", required: true)]
        public string NamespaceId { get; set; } = null!;

        /// <summary>
        /// The permission to assign. Must be one of admin, write, or read (case-insensitive)
        /// </summary>
        [Input("permission", required: true)]
        public string Permission { get; set; } = null!;

        public GetServiceAccountNamespaceAccessArgs()
        {
        }
        public static new GetServiceAccountNamespaceAccessArgs Empty => new GetServiceAccountNamespaceAccessArgs();
    }
}
