// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Inputs
{

    public sealed class NamespaceExportSinkS3GetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The AWS account ID associated with the S3 bucket and the assumed role.
        /// </summary>
        [Input("awsAccountId", required: true)]
        public Input<string> AwsAccountId { get; set; } = null!;

        /// <summary>
        /// The name of the destination S3 bucket where Temporal will send data.
        /// </summary>
        [Input("bucketName", required: true)]
        public Input<string> BucketName { get; set; } = null!;

        /// <summary>
        /// The AWS Key Management Service (KMS) ARN used for encryption.
        /// </summary>
        [Input("kmsArn", required: true)]
        public Input<string> KmsArn { get; set; } = null!;

        /// <summary>
        /// The region where the S3 bucket is located.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        /// <summary>
        /// The IAM role that Temporal Cloud assumes for writing records to the customer's S3 bucket.
        /// </summary>
        [Input("roleName", required: true)]
        public Input<string> RoleName { get; set; } = null!;

        public NamespaceExportSinkS3GetArgs()
        {
        }
        public static new NamespaceExportSinkS3GetArgs Empty => new NamespaceExportSinkS3GetArgs();
    }
}
