// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GripSecurity.Temporalcloud.Inputs
{

    public sealed class NamespaceExportSinkGcsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the destination GCS bucket where Temporal will send data.
        /// </summary>
        [Input("bucketName", required: true)]
        public Input<string> BucketName { get; set; } = null!;

        /// <summary>
        /// The GCP project ID associated with the GCS bucket and service account.
        /// </summary>
        [Input("gcpProjectId", required: true)]
        public Input<string> GcpProjectId { get; set; } = null!;

        /// <summary>
        /// The region of the gcs bucket
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        /// <summary>
        /// The customer service account ID that Temporal Cloud impersonates for writing records to the customer's GCS bucket.
        /// </summary>
        [Input("serviceAccountId", required: true)]
        public Input<string> ServiceAccountId { get; set; } = null!;

        public NamespaceExportSinkGcsGetArgs()
        {
        }
        public static new NamespaceExportSinkGcsGetArgs Empty => new NamespaceExportSinkGcsGetArgs();
    }
}
