// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Temporalcloud.Inputs
{

    public sealed class NamespaceCodecServerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The endpoint of the codec server. Must begin with "https".
        /// </summary>
        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        /// <summary>
        /// If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
        /// </summary>
        [Input("includeCrossOriginCredentials")]
        public Input<bool>? IncludeCrossOriginCredentials { get; set; }

        /// <summary>
        /// If true, Temporal Cloud will pass the access token to the codec server upon each request.
        /// </summary>
        [Input("passAccessToken")]
        public Input<bool>? PassAccessToken { get; set; }

        public NamespaceCodecServerArgs()
        {
        }
        public static new NamespaceCodecServerArgs Empty => new NamespaceCodecServerArgs();
    }
}
