// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApikeyArgs, ApikeyState } from "./apikey";
export type Apikey = import("./apikey").Apikey;
export const Apikey: typeof import("./apikey").Apikey = null as any;
utilities.lazyLoad(exports, ["Apikey"], () => require("./apikey"));

export { ConnectivityRuleArgs, ConnectivityRuleState } from "./connectivityRule";
export type ConnectivityRule = import("./connectivityRule").ConnectivityRule;
export const ConnectivityRule: typeof import("./connectivityRule").ConnectivityRule = null as any;
utilities.lazyLoad(exports, ["ConnectivityRule"], () => require("./connectivityRule"));

export { GetNamespaceArgs, GetNamespaceResult, GetNamespaceOutputArgs } from "./getNamespace";
export const getNamespace: typeof import("./getNamespace").getNamespace = null as any;
export const getNamespaceOutput: typeof import("./getNamespace").getNamespaceOutput = null as any;
utilities.lazyLoad(exports, ["getNamespace","getNamespaceOutput"], () => require("./getNamespace"));

export { GetNamespacesResult } from "./getNamespaces";
export const getNamespaces: typeof import("./getNamespaces").getNamespaces = null as any;
export const getNamespacesOutput: typeof import("./getNamespaces").getNamespacesOutput = null as any;
utilities.lazyLoad(exports, ["getNamespaces","getNamespacesOutput"], () => require("./getNamespaces"));

export { GetNexusEndpointArgs, GetNexusEndpointResult, GetNexusEndpointOutputArgs } from "./getNexusEndpoint";
export const getNexusEndpoint: typeof import("./getNexusEndpoint").getNexusEndpoint = null as any;
export const getNexusEndpointOutput: typeof import("./getNexusEndpoint").getNexusEndpointOutput = null as any;
utilities.lazyLoad(exports, ["getNexusEndpoint","getNexusEndpointOutput"], () => require("./getNexusEndpoint"));

export { GetNexusEndpointsResult } from "./getNexusEndpoints";
export const getNexusEndpoints: typeof import("./getNexusEndpoints").getNexusEndpoints = null as any;
export const getNexusEndpointsOutput: typeof import("./getNexusEndpoints").getNexusEndpointsOutput = null as any;
utilities.lazyLoad(exports, ["getNexusEndpoints","getNexusEndpointsOutput"], () => require("./getNexusEndpoints"));

export { GetRegionsResult } from "./getRegions";
export const getRegions: typeof import("./getRegions").getRegions = null as any;
export const getRegionsOutput: typeof import("./getRegions").getRegionsOutput = null as any;
utilities.lazyLoad(exports, ["getRegions","getRegionsOutput"], () => require("./getRegions"));

export { GetScimGroupArgs, GetScimGroupResult, GetScimGroupOutputArgs } from "./getScimGroup";
export const getScimGroup: typeof import("./getScimGroup").getScimGroup = null as any;
export const getScimGroupOutput: typeof import("./getScimGroup").getScimGroupOutput = null as any;
utilities.lazyLoad(exports, ["getScimGroup","getScimGroupOutput"], () => require("./getScimGroup"));

export { GetServiceAccountArgs, GetServiceAccountResult, GetServiceAccountOutputArgs } from "./getServiceAccount";
export const getServiceAccount: typeof import("./getServiceAccount").getServiceAccount = null as any;
export const getServiceAccountOutput: typeof import("./getServiceAccount").getServiceAccountOutput = null as any;
utilities.lazyLoad(exports, ["getServiceAccount","getServiceAccountOutput"], () => require("./getServiceAccount"));

export { GetServiceAccountsResult } from "./getServiceAccounts";
export const getServiceAccounts: typeof import("./getServiceAccounts").getServiceAccounts = null as any;
export const getServiceAccountsOutput: typeof import("./getServiceAccounts").getServiceAccountsOutput = null as any;
utilities.lazyLoad(exports, ["getServiceAccounts","getServiceAccountsOutput"], () => require("./getServiceAccounts"));

export { GetUserArgs, GetUserResult, GetUserOutputArgs } from "./getUser";
export const getUser: typeof import("./getUser").getUser = null as any;
export const getUserOutput: typeof import("./getUser").getUserOutput = null as any;
utilities.lazyLoad(exports, ["getUser","getUserOutput"], () => require("./getUser"));

export { GetUsersResult } from "./getUsers";
export const getUsers: typeof import("./getUsers").getUsers = null as any;
export const getUsersOutput: typeof import("./getUsers").getUsersOutput = null as any;
utilities.lazyLoad(exports, ["getUsers","getUsersOutput"], () => require("./getUsers"));

export { GroupAccessArgs, GroupAccessState } from "./groupAccess";
export type GroupAccess = import("./groupAccess").GroupAccess;
export const GroupAccess: typeof import("./groupAccess").GroupAccess = null as any;
utilities.lazyLoad(exports, ["GroupAccess"], () => require("./groupAccess"));

export { MetricsEndpointArgs, MetricsEndpointState } from "./metricsEndpoint";
export type MetricsEndpoint = import("./metricsEndpoint").MetricsEndpoint;
export const MetricsEndpoint: typeof import("./metricsEndpoint").MetricsEndpoint = null as any;
utilities.lazyLoad(exports, ["MetricsEndpoint"], () => require("./metricsEndpoint"));

export { NamespaceArgs, NamespaceState } from "./namespace";
export type Namespace = import("./namespace").Namespace;
export const Namespace: typeof import("./namespace").Namespace = null as any;
utilities.lazyLoad(exports, ["Namespace"], () => require("./namespace"));

export { NamespaceExportSinkArgs, NamespaceExportSinkState } from "./namespaceExportSink";
export type NamespaceExportSink = import("./namespaceExportSink").NamespaceExportSink;
export const NamespaceExportSink: typeof import("./namespaceExportSink").NamespaceExportSink = null as any;
utilities.lazyLoad(exports, ["NamespaceExportSink"], () => require("./namespaceExportSink"));

export { NamespaceSearchAttributeArgs, NamespaceSearchAttributeState } from "./namespaceSearchAttribute";
export type NamespaceSearchAttribute = import("./namespaceSearchAttribute").NamespaceSearchAttribute;
export const NamespaceSearchAttribute: typeof import("./namespaceSearchAttribute").NamespaceSearchAttribute = null as any;
utilities.lazyLoad(exports, ["NamespaceSearchAttribute"], () => require("./namespaceSearchAttribute"));

export { NexusEndpointArgs, NexusEndpointState } from "./nexusEndpoint";
export type NexusEndpoint = import("./nexusEndpoint").NexusEndpoint;
export const NexusEndpoint: typeof import("./nexusEndpoint").NexusEndpoint = null as any;
utilities.lazyLoad(exports, ["NexusEndpoint"], () => require("./nexusEndpoint"));

export * from "./provider";
import { Provider } from "./provider";

export { ServiceAccountArgs, ServiceAccountState } from "./serviceAccount";
export type ServiceAccount = import("./serviceAccount").ServiceAccount;
export const ServiceAccount: typeof import("./serviceAccount").ServiceAccount = null as any;
utilities.lazyLoad(exports, ["ServiceAccount"], () => require("./serviceAccount"));

export { UserArgs, UserState } from "./user";
export type User = import("./user").User;
export const User: typeof import("./user").User = null as any;
utilities.lazyLoad(exports, ["User"], () => require("./user"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "temporalcloud:index/apikey:Apikey":
                return new Apikey(name, <any>undefined, { urn })
            case "temporalcloud:index/connectivityRule:ConnectivityRule":
                return new ConnectivityRule(name, <any>undefined, { urn })
            case "temporalcloud:index/groupAccess:GroupAccess":
                return new GroupAccess(name, <any>undefined, { urn })
            case "temporalcloud:index/metricsEndpoint:MetricsEndpoint":
                return new MetricsEndpoint(name, <any>undefined, { urn })
            case "temporalcloud:index/namespace:Namespace":
                return new Namespace(name, <any>undefined, { urn })
            case "temporalcloud:index/namespaceExportSink:NamespaceExportSink":
                return new NamespaceExportSink(name, <any>undefined, { urn })
            case "temporalcloud:index/namespaceSearchAttribute:NamespaceSearchAttribute":
                return new NamespaceSearchAttribute(name, <any>undefined, { urn })
            case "temporalcloud:index/nexusEndpoint:NexusEndpoint":
                return new NexusEndpoint(name, <any>undefined, { urn })
            case "temporalcloud:index/serviceAccount:ServiceAccount":
                return new ServiceAccount(name, <any>undefined, { urn })
            case "temporalcloud:index/user:User":
                return new User(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("temporalcloud", "index/apikey", _module)
pulumi.runtime.registerResourceModule("temporalcloud", "index/connectivityRule", _module)
pulumi.runtime.registerResourceModule("temporalcloud", "index/groupAccess", _module)
pulumi.runtime.registerResourceModule("temporalcloud", "index/metricsEndpoint", _module)
pulumi.runtime.registerResourceModule("temporalcloud", "index/namespace", _module)
pulumi.runtime.registerResourceModule("temporalcloud", "index/namespaceExportSink", _module)
pulumi.runtime.registerResourceModule("temporalcloud", "index/namespaceSearchAttribute", _module)
pulumi.runtime.registerResourceModule("temporalcloud", "index/nexusEndpoint", _module)
pulumi.runtime.registerResourceModule("temporalcloud", "index/serviceAccount", _module)
pulumi.runtime.registerResourceModule("temporalcloud", "index/user", _module)
pulumi.runtime.registerResourcePackage("temporalcloud", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:temporalcloud") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
